import { useState } from 'react';
import { useLanguage } from '../../i18n/LanguageContext';
import { faLabel } from '../../utils/localizeContent';
import { useAppStore } from '../../store/useAppStore';
import { FileText, Download, Copy, CheckCheck } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface ReportData {
  title: string;
  severity: 'Critical' | 'High' | 'Medium' | 'Low' | 'Informational';
  target: string;
  affectedUrl: string;
  cve: string;
  description: string;
  impact: string;
  reproduction: string;
  fix: string;
  reporter: string;
  date: string;
}

const CVSS: Record<string, { score: string; color: string }> = {
  Critical: { score: '9.0-10.0', color: 'text-red-500' },
  High: { score: '7.0-8.9', color: 'text-orange-400' },
  Medium: { score: '4.0-6.9', color: 'text-yellow-400' },
  Low: { score: '0.1-3.9', color: 'text-green-400' },
  Informational: { score: '0.0', color: 'text-blue-400' },
};

export function ReportGenerator() {
  const { locale } = useLanguage();
  const tx = (value: string, replacements: Record<string, string | number> = {}) => locale === 'fa' ? faLabel(value, replacements) : Object.entries(replacements).reduce((text, [key, replacement]) => text.replaceAll(`{{${key}}}`, String(replacement)), value);
  const { darkMode, userName } = useAppStore();
  const [copied, setCopied] = useState(false);

  const [report, setReport] = useState<ReportData>({
    title: tx('SQL Injection in Login Endpoint'),
    severity: 'Critical',
    target: 'example.com',
    affectedUrl: 'https://example.com/api/login',
    cve: 'CWE-89',
    description: tx('The login endpoint is vulnerable to SQL injection via the username parameter. User-supplied input is concatenated directly into the SQL query without sanitization.'),
    impact: tx('An unauthenticated attacker can bypass authentication, extract all user credentials from the database, and potentially achieve remote code execution on the database server.'),
    reproduction: `1. Navigate to https://example.com/login
2. Enter the following in the username field: admin'--
3. Enter any password
4. Click "Login"
5. Observe that authentication is bypassed and you are logged in as admin`,
    fix: `1. Use parameterized queries / prepared statements
2. Apply input validation with strict whitelisting
3. Use a database account with minimum required privileges
4. Implement proper error handling that doesn't expose SQL errors`,
    reporter: userName || (locale === 'fa' ? '??????? ?????' : 'Security Researcher'),
    date: new Date().toISOString().split('T')[0],
  });

  const update = (field: keyof ReportData, value: string) => {
    setReport(prev => ({ ...prev, [field]: value }));
  };

  const generateMarkdown = (): string => {
    return `# ${tx('Bug Report')}: ${report.title}

**Severity:** ${tx(report.severity)} (CVSS: ${CVSS[report.severity].score})
**${tx('Target')}:** ${report.target}
**${tx('Affected URL')}:** ${report.affectedUrl}
**${tx('Reference')}:** ${report.cve}
**${tx('Reporter')}:** ${report.reporter}
**${tx('Date')}:** ${report.date}

---

## ${tx('Description')}

${report.description}

## ${tx('Impact')}

${report.impact}

## ${tx('Steps to Reproduce')}

${report.reproduction}

## ${tx('Suggested Fix')}

${report.fix}

---

*${tx('This report was generated with HackPath Report Generator. For educational purposes.')}*`;
  };

  const copyMarkdown = () => {
    navigator.clipboard?.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadPDF = () => {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const severity = report.severity;
    const cvssScore = CVSS[severity].score;

    // Header
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, 210, 35, 'F');
    doc.setFillColor(
      severity === 'Critical' ? 220 : severity === 'High' ? 249 : severity === 'Medium' ? 245 : 34,
      severity === 'Critical' ? 38 : severity === 'High' ? 115 : severity === 'Medium' ? 158 : 197,
      severity === 'Critical' ? 38 : severity === 'High' ? 22 : severity === 'Medium' ? 11 : 94
    );
    doc.rect(0, 0, 5, 297, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text('Vulnerability Report', 15, 15);
    doc.setFontSize(10);
    doc.text(`Generated by HackPath Security Lab • ${report.date}`, 15, 25);

    let y = 45;
    doc.setTextColor(0, 0, 0);

    const addSection = (title: string, content: string) => {
      if (y > 250) { doc.addPage(); y = 20; }
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text(title, 15, y);
      y += 6;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      const lines = doc.splitTextToSize(content, 175);
      lines.forEach((line: string) => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.text(line, 15, y);
        y += 5;
      });
      y += 5;
    };

    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text(report.title, 15, y);
    y += 12;

    // Meta
    const meta = [
      `Severity: ${severity} (CVSS: ${cvssScore})`,
      `Target: ${report.target}`,
      `URL: ${report.affectedUrl}`,
      `Reference: ${report.cve}`,
      `Reporter: ${report.reporter}`,
    ];
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    meta.forEach(m => {
      doc.setTextColor(71, 85, 105);
      doc.text(m, 15, y);
      y += 6;
    });
    y += 5;

    addSection('Description', report.description);
    addSection('Impact', report.impact);
    addSection('Steps to Reproduce', report.reproduction);
    addSection('Remediation', report.fix);

    doc.save(`report-${report.title.replace(/\s+/g, '-').toLowerCase()}.pdf`);
  };

  return (
    <div className={`min-h-screen ${darkMode ? 'bg-slate-950' : 'bg-slate-50'}`}>
      <div className={`border-b ${darkMode ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'}`}>
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 bg-gradient-to-br from-green-500 to-teal-600 rounded-xl flex items-center justify-center">
              <FileText size={20} className="text-white" />
            </div>
            <h1 className={`text-3xl font-black ${darkMode ? 'text-white' : 'text-slate-900'}`}>{tx('Report Generator')}</h1>
          </div>
          <p className={`text-base ${darkMode ? 'text-slate-400' : 'text-slate-500'}`}>
            {tx('Generate professional vulnerability reports in Markdown and PDF formats')}
          </p>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Form */}
          <div className="space-y-4">
            <div className={`p-6 rounded-2xl border ${darkMode ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'}`}>
              <h2 className={`font-bold mb-4 ${darkMode ? 'text-white' : 'text-slate-900'}`}>{tx('Report Details')}</h2>
              <div className="space-y-4">
                <div>
                  <label className={`block text-xs font-semibold uppercase tracking-wider mb-1.5 ${darkMode ? 'text-slate-400' : 'text-slate-500'}`}>{tx('Title *')}</label>
                  <input
                    value={report.title}
                    onChange={e => update('title', e.target.value)}
                    className={`w-full px-3 py-2.5 rounded-xl border text-sm outline-none ${darkMode ? 'bg-slate-800 border-slate-700 text-white focus:border-green-500' : 'bg-white border-slate-300 text-slate-900 focus:border-green-500'}`}
                  />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className={`block text-xs font-semibold uppercase tracking-wider mb-1.5 ${darkMode ? 'text-slate-400' : 'text-slate-500'}`}>{tx('Severity *')}</label>
                    <select
                      value={tx(report.severity)}
                      onChange={e => update('severity', e.target.value)}
                      className={`w-full px-3 py-2.5 rounded-xl border text-sm outline-none ${darkMode ? 'bg-slate-800 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'}`}>
                      {Object.keys(CVSS).map(s => <option key={s}>{s}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className={`block text-xs font-semibold uppercase tracking-wider mb-1.5 ${darkMode ? 'text-slate-400' : 'text-slate-500'}`}>{tx('Date')}</label>
                    <input
                      type="date"
                      value={report.date}
                      onChange={e => update('date', e.target.value)}
                      className={`technical-ltr w-full px-3 py-2.5 rounded-xl border text-sm outline-none ${darkMode ? 'bg-slate-800 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'}`}
                    />
                  </div>
                </div>
                <div>
                  <label className={`block text-xs font-semibold uppercase tracking-wider mb-1.5 ${darkMode ? 'text-slate-400' : 'text-slate-500'}`}>{tx('Target Domain')}</label>
                  <input
                    value={report.target}
                    onChange={e => update('target', e.target.value)}
                    className={`technical-ltr w-full px-3 py-2.5 rounded-xl border text-sm outline-none ${darkMode ? 'bg-slate-800 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'}`}
                  />
                </div>
                <div>
                  <label className={`block text-xs font-semibold uppercase tracking-wider mb-1.5 ${darkMode ? 'text-slate-400' : 'text-slate-500'}`}>{tx('Affected URL')}</label>
                  <input
                    value={report.affectedUrl}
                    onChange={e => update('affectedUrl', e.target.value)}
                    className={`technical-ltr w-full px-3 py-2.5 rounded-xl border text-sm outline-none ${darkMode ? 'bg-slate-800 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'}`}
                  />
                </div>
                <div>
                  <label className={`block text-xs font-semibold uppercase tracking-wider mb-1.5 ${darkMode ? 'text-slate-400' : 'text-slate-500'}`}>{tx('CWE / CVE Reference')}</label>
                  <input
                    value={report.cve}
                    onChange={e => update('cve', e.target.value)}
                    placeholder="e.g. CWE-89, CVE-2024-XXXXX"
                    className={`technical-ltr w-full px-3 py-2.5 rounded-xl border text-sm outline-none ${darkMode ? 'bg-slate-800 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'}`}
                  />
                </div>
                <div>
                  <label className={`block text-xs font-semibold uppercase tracking-wider mb-1.5 ${darkMode ? 'text-slate-400' : 'text-slate-500'}`}>{tx('Reporter Name')}</label>
                  <input
                    value={report.reporter}
                    onChange={e => update('reporter', e.target.value)}
                    className={`w-full px-3 py-2.5 rounded-xl border text-sm outline-none ${darkMode ? 'bg-slate-800 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'}`}
                  />
                </div>
                {[
                  { field: 'description' as const, label: tx('Description *'), rows: 4 },
                  { field: 'impact' as const, label: tx('Impact *'), rows: 3 },
                  { field: 'reproduction' as const, label: tx('Steps to Reproduce *'), rows: 6 },
                  { field: 'fix' as const, label: tx('Suggested Fix *'), rows: 4 },
                ].map(f => (
                  <div key={f.field}>
                    <label className={`block text-xs font-semibold uppercase tracking-wider mb-1.5 ${darkMode ? 'text-slate-400' : 'text-slate-500'}`}>{f.label}</label>
                    <textarea
                      value={report[f.field]}
                      onChange={e => update(f.field, e.target.value)}
                      rows={f.rows}
                      className={`${f.field === 'reproduction' || f.field === 'fix' ? 'technical-ltr ' : ''}w-full px-3 py-2.5 rounded-xl border text-sm resize-y outline-none ${darkMode ? 'bg-slate-800 border-slate-700 text-white' : 'bg-white border-slate-300 text-slate-900'}`}
                    />
                  </div>
                ))}
              </div>
            </div>

            {/* Actions */}
            <div className="flex gap-3">
              <button
                onClick={copyMarkdown}
                className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-xl font-semibold text-sm border transition-colors ${
                  darkMode ? 'border-slate-700 text-slate-300 hover:bg-slate-800' : 'border-slate-300 text-slate-700 hover:bg-slate-100'
                }`}>
                {copied ? <CheckCheck size={16} className="text-green-400" /> : <Copy size={16} />}
                {copied ? tx('Copied!') : tx('Copy Markdown')}
              </button>
              <button
                onClick={downloadPDF}
                className="flex-1 flex items-center justify-center gap-2 bg-green-500 hover:bg-green-400 text-white font-semibold py-3 rounded-xl text-sm transition-colors">
                <Download size={16} />
                {tx('Download PDF')}
              </button>
            </div>
          </div>

          {/* Preview */}
          <div>
            <div className={`rounded-2xl border overflow-hidden sticky top-20 ${darkMode ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'}`}>
              <div className={`flex items-center justify-between px-5 py-3.5 border-b ${darkMode ? 'border-slate-800 bg-slate-800' : 'border-slate-200 bg-slate-50'}`}>
                <span className={`text-xs font-semibold ${darkMode ? 'text-slate-400' : 'text-slate-500'}`}>{tx('MARKDOWN PREVIEW')}</span>
                <span className={`text-xs px-2 py-0.5 rounded font-semibold ${CVSS[report.severity].color} bg-current/10`}>
                  {tx(report.severity)}
                </span>
              </div>
              <pre className={`technical-ltr p-5 text-xs font-mono leading-relaxed overflow-auto max-h-[70vh] whitespace-pre-wrap ${darkMode ? 'text-slate-300' : 'text-slate-700'}`}>
                {generateMarkdown()}
              </pre>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

