const faLabels: Record<string, string> = {
  All: 'همه',
  Critical: 'بحرانی',
  High: 'زیاد',
  Medium: 'متوسط',
  Low: 'کم',
  Informational: 'اطلاعاتی',
  Apprentice: 'مبتدی',
  Practitioner: 'تمرین‌کننده',
  Expert: 'حرفه‌ای',
  Vulnerabilities: 'آسیب‌پذیری‌ها',
  'In-depth coverage of {{count}}+ web security vulnerability categories': 'پوشش عمیق بیش از {{count}} دسته آسیب‌پذیری امنیت وب',
  'Search vulnerabilities...': 'جستجوی آسیب‌پذیری‌ها...',
  'No vulnerabilities found': 'هیچ آسیب‌پذیری‌ای پیدا نشد',
  'Vulnerability Not Found': 'آسیب‌پذیری پیدا نشد',
  Back: 'بازگشت',
  'All Vulnerabilities': 'همه آسیب‌پذیری‌ها',
  Overview: 'نمای کلی',
  'Code Examples': 'نمونه کدها',
  Detection: 'تشخیص',
  Impact: 'اثر',
  'Attack Scenarios': 'سناریوهای حمله',
  'Common Developer Mistakes': 'اشتباه‌های رایج توسعه‌دهندگان',
  'Example Payloads': 'نمونه Payloadها',
  Remediation: 'راهکار اصلاح',
  References: 'منابع',
  'Quick Practice': 'تمرین سریع',
  'Vulnerable Code': 'کد آسیب‌پذیر',
  'Fixed Code': 'کد اصلاح‌شده',
  'Manual Detection': 'تشخیص دستی',
  'Automated Tools': 'ابزارهای خودکار',
  Labs: 'آزمایشگاه‌ها',
  'Practice web security vulnerabilities with {{count}} interactive challenges': 'آسیب‌پذیری‌های امنیت وب را با {{count}} چالش تعاملی تمرین کنید',
  'Labs Completed': 'آزمایشگاه تکمیل‌شده',
  'Live Simulations': 'شبیه‌سازی‌های زنده',
  'Search labs...': 'جستجوی آزمایشگاه‌ها...',
  'All Categories': 'همه دسته‌بندی‌ها',
  'Show completed': 'نمایش تکمیل‌شده‌ها',
  'Live only': 'فقط زنده',
  'Showing {{shown}} of {{total}} labs': 'نمایش {{shown}} از {{total}} آزمایشگاه',
  Weekly: 'هفتگی',
  Live: 'زنده',
  Guide: 'راهنما',
  'No labs found': 'هیچ آزمایشگاهی پیدا نشد',
  'Try adjusting your filters': 'فیلترها را تغییر دهید',
  'Learning Paths': 'مسیرهای یادگیری',
  'Structured curricula designed for different goals and skill levels': 'برنامه‌های آموزشی ساختاریافته برای هدف‌ها و سطح‌های مهارتی متفاوت',
  Curriculum: 'برنامه آموزشی',
  Module: 'ماژول',
  completed: 'تکمیل‌شده',
  estimated: 'تخمینی',
  'Next up': 'بعدی',
  Continue: 'ادامه',
  'Path Complete!': 'مسیر کامل شد!',
  'Security Glossary': 'واژه‌نامه امنیت',
  '{{count}} essential web security terms defined and explained': '{{count}} اصطلاح ضروری امنیت وب تعریف و توضیح داده شده‌اند',
  'Search terms...': 'جستجوی اصطلاح‌ها...',
  'Deep dive': 'بررسی عمیق',
  Example: 'مثال',
  'No terms found': 'هیچ اصطلاحی پیدا نشد',
  'Encoder / Decoder': 'رمزگذار / رمزگشا',
  'Encode and decode data in various formats: Base64, URL, HTML, JWT': 'داده‌ها را در قالب‌های Base64، URL، HTML و JWT رمزگذاری و رمزگشایی کنید',
  Input: 'ورودی',
  Output: 'خروجی',
  'Enter text to process...': 'متن را برای پردازش وارد کنید...',
  'Paste your JWT token here...': 'توکن JWT خود را اینجا بچسبانید...',
  'Output will appear here...': 'خروجی اینجا نمایش داده می‌شود...',
  Copy: 'کپی',
  'Copied!': 'کپی شد!',
  'Security Note': 'نکته امنیتی',
  'Quick Examples': 'نمونه‌های سریع',
  'Base64 Encode': 'رمزگذاری Base64',
  'Base64 Decode': 'رمزگشایی Base64',
  'URL Encode': 'رمزگذاری URL',
  'URL Decode': 'رمزگشایی URL',
  'HTML Encode': 'رمزگذاری HTML',
  'HTML Decode': 'رمزگشایی HTML',
  'JWT Decode': 'رمزگشایی JWT',
  'HTTP Interceptor Simulator': 'شبیه‌ساز رهگیر HTTP',
  'Educational simulation of HTTP request interception and modification. Not a real proxy.': 'شبیه‌سازی آموزشی رهگیری و تغییر درخواست HTTP. این ابزار پراکسی واقعی نیست.',
  'Educational simulation only — no real requests are made': 'فقط شبیه‌سازی آموزشی — هیچ درخواست واقعی ارسال نمی‌شود',
  'Simulate Response Type': 'شبیه‌سازی نوع پاسخ',
  '200 Normal Response': 'پاسخ عادی ۲۰۰',
  'IDOR - Admin Data Exposed': 'IDOR - داده مدیر افشا شد',
  '403 Forbidden': '۴۰۳ ممنوع',
  '500 Error (Info Leak)': 'خطای ۵۰۰ (نشت اطلاعات)',
  'HTTP Request Editor': 'ویرایشگر درخواست HTTP',
  Headers: 'سرآیندها',
  'Header name': 'نام سرآیند',
  Value: 'مقدار',
  'Add Header': 'افزودن سرآیند',
  'Send Request': 'ارسال درخواست',
  'Sending...': 'در حال ارسال...',
  'HTTP Response': 'پاسخ HTTP',
  'Sending request...': 'در حال ارسال درخواست...',
  'Response will appear here after sending the request...': 'پس از ارسال درخواست، پاسخ اینجا نمایش داده می‌شود...',
  'Testing Tips': 'نکته‌های تست',
  'Report Generator': 'گزارش‌ساز',
  'Generate professional vulnerability reports in Markdown and PDF formats': 'گزارش‌های حرفه‌ای آسیب‌پذیری را در قالب Markdown و PDF بسازید',
  'Report Details': 'جزئیات گزارش',
  'Title *': 'عنوان *',
  'Severity *': 'شدت *',
  Date: 'تاریخ',
  'Target Domain': 'دامنه هدف',
  'Affected URL': 'نشانی آسیب‌دیده',
  'CWE / CVE Reference': 'مرجع CWE / CVE',
  'Reporter Name': 'نام گزارش‌دهنده',
  'Description *': 'توضیح *',
  'Impact *': 'اثر *',
  'Steps to Reproduce *': 'مراحل بازتولید *',
  'Suggested Fix *': 'راهکار پیشنهادی *',
  'Copy Markdown': 'کپی Markdown',
  'Download PDF': 'دانلود PDF',
  'MARKDOWN PREVIEW': 'پیش‌نمایش Markdown',
  'Bug Report': 'گزارش باگ',
  Severity: 'شدت',
  Target: 'هدف',
  Reference: 'مرجع',
  Reporter: 'گزارش‌دهنده',
  Description: 'توضیح',
  'Steps to Reproduce': 'مراحل بازتولید',
  'Suggested Fix': 'راهکار پیشنهادی',
  'This report was generated with HackPath Report Generator. For educational purposes.': 'این گزارش با گزارش‌ساز HackPath تولید شده است. فقط برای اهداف آموزشی.',
  'SQL Injection in Login Endpoint': 'تزریق SQL در نقطه ورود',
  'The login endpoint is vulnerable to SQL injection via the username parameter. User-supplied input is concatenated directly into the SQL query without sanitization.': 'نقطه ورود از طریق پارامتر نام کاربری در برابر تزریق SQL آسیب‌پذیر است. ورودی کاربر بدون پاک‌سازی مستقیماً به پرس‌وجوی SQL متصل می‌شود.',
  'An unauthenticated attacker can bypass authentication, extract all user credentials from the database, and potentially achieve remote code execution on the database server.': 'مهاجم بدون احراز هویت می‌تواند احراز هویت را دور بزند، همه اعتبارنامه‌های کاربران را از پایگاه داده استخراج کند و احتمالاً روی سرور پایگاه داده اجرای کد انجام دهد.',
  Leaderboard: 'جدول امتیازها',
  'Your personal time trial records': 'رکوردهای شخصی زمان‌گیری شما',
  'Timed Labs': 'آزمایشگاه‌های زمان‌دار',
  'Average Time': 'میانگین زمان',
  'Fastest Time': 'سریع‌ترین زمان',
  'Clear All Records': 'پاک کردن همه رکوردها',
  'No time records yet': 'هنوز رکورد زمانی ندارید',
  'Enable the timer in any lab and complete it to record your time!': 'زمان‌سنج را در هر آزمایشگاه فعال کنید و آن را کامل کنید تا زمان شما ثبت شود!',
  Resources: 'منابع',
  'Methodology, templates, cheat sheets, and payload references': 'روش‌شناسی، قالب‌ها، برگه‌های تقلب و مرجع payloadها',
  'Bug Bounty Methodology': 'روش‌شناسی باگ‌بانتی',
  Step: 'گام',
  Reconnaissance: 'شناسایی',
  Enumeration: 'فهرست‌برداری',
  Exploitation: 'بهره‌برداری',
  'Post-Exploitation': 'پس از بهره‌برداری',
  Reporting: 'گزارش‌دهی',
  'Cheat Sheets': 'برگه‌های تقلب',
  'Payload Reference': 'مرجع Payload',
  'Bug Report Template': 'قالب گزارش باگ',
  'Copy Template': 'کپی قالب',
  'External Resources': 'منابع بیرونی',
  Dashboard: 'داشبورد',
  'Your security learning progress and statistics': 'پیشرفت و آمار یادگیری امنیت شما',
  'Total XP': 'کل XP',
  'Labs Done': 'آزمایشگاه‌های انجام‌شده',
  Badges: 'نشان‌ها',
  'Timed Runs': 'اجرای زمان‌دار',
  'Start timing!': 'زمان‌گیری را شروع کنید!',
  of: 'از',
  'XP Progress': 'پیشرفت XP',
  'Completion by Category': 'تکمیل بر اساس دسته‌بندی',
  'Completion by Difficulty': 'تکمیل بر اساس دشواری',
  'Difficulty Breakdown': 'جزئیات دشواری',
  'Recent Badges': 'نشان‌های اخیر',
  'View all': 'مشاهده همه',
  'View Full Leaderboard': 'مشاهده جدول کامل امتیازها',
  'Complete labs to earn badges!': 'برای گرفتن نشان‌ها آزمایشگاه‌ها را کامل کنید!',
  'Certificate Progress': 'پیشرفت گواهی',
  'Download Certificate': 'دانلود گواهی',
};

const faContent: Record<string, string> = {
  'Cross-Site Request Forgery (CSRF)': 'جعل درخواست میان‌سایتی (CSRF)',
  'Cross-Site Scripting (XSS)': 'اسکریپت‌نویسی میان‌سایتی (XSS)',
  'SQL Injection': 'تزریق SQL',
  'Remote Code Execution (RCE)': 'اجرای کد از راه دور (RCE)',
  'XML External Entity (XXE)': 'موجودیت خارجی XML (XXE)',
  'Server-Side Request Forgery (SSRF)': 'جعل درخواست سمت سرور (SSRF)',
  'Bug Bounty Hunter': 'شکارچی باگ‌بانتی',
  'Web Pentester': 'تستر نفوذ وب',
  'OWASP Top 10': 'ده مورد برتر OWASP',
  'Advanced Researcher': 'پژوهشگر پیشرفته',
  'Reconnaissance & OSINT': 'شناسایی و OSINT',
  'Injection Vulnerabilities': 'آسیب‌پذیری‌های تزریق',
  'Client-Side Attacks': 'حمله‌های سمت کلاینت',
  'Server-Side Vulnerabilities': 'آسیب‌پذیری‌های سمت سرور',
  'Authentication & Authorization': 'احراز هویت و مجوزدهی',
  'Complete bug bounty methodology from reconnaissance to reporting. Follow the exact workflow used by top bounty hunters.': 'روش‌شناسی کامل باگ‌بانتی از شناسایی تا گزارش‌دهی؛ همان جریان کاری شکارچیان حرفه‌ای باگ را دنبال کنید.',
  'Find targets and gather information': 'هدف‌ها را پیدا کنید و اطلاعات جمع‌آوری کنید',
  'SQL, NoSQL, Command injection': 'تزریق SQL، NoSQL و فرمان',
  'XSS, CSRF, Clickjacking': 'XSS، CSRF و کلیک‌ربایی',
  'SSRF, XXE, Path Traversal': 'SSRF، XXE و پیمایش مسیر',
  'JWT, IDOR, Auth bypass': 'JWT، IDOR و دور زدن احراز هویت',
  'Write professional vulnerability reports': 'گزارش‌های حرفه‌ای آسیب‌پذیری بنویسید',
  'SQL Injection (SQLi) is a web security vulnerability that allows attackers to interfere with the queries that an application makes to its database. It allows attackers to view data they are not normally able to retrieve, modify or delete data, and in some cases execute commands on the underlying server.': 'تزریق SQL آسیب‌پذیری‌ای در امنیت وب است که به مهاجم اجازه می‌دهد در پرس‌وجوهای برنامه به پایگاه داده دخالت کند؛ داده‌های غیرمجاز را ببیند، تغییر دهد یا حذف کند و گاهی روی سرور فرمان اجرا کند.',
  'Cross-site scripting (XSS) is a client-side code injection attack. The attacker aims to execute malicious scripts in a web browser of the victim by including malicious code in a legitimate web page or web application. Types include Reflected, Stored, and DOM-based XSS.': 'XSS حمله تزریق کد سمت کاربر است؛ مهاجم کد مخرب را در صفحه یا برنامه وب معتبر قرار می‌دهد تا در مرورگر قربانی اجرا شود. انواع آن شامل بازتابی، ذخیره‌شده و مبتنی بر DOM است.',
  "CSRF is an attack that forces authenticated users to submit a request to a web application against which they are currently authenticated. CSRF attacks exploit the trust a site has in the user's browser, tricking victims into performing unintended actions.": 'CSRF کاربر احراز هویت‌شده را وادار می‌کند در برنامه‌ای که در آن وارد شده درخواست ناخواسته ارسال کند. این حمله از اعتماد سایت به مرورگر کاربر سوءاستفاده می‌کند.',
  "SSRF is a web security vulnerability that allows attackers to induce the server-side application to make HTTP requests to an arbitrary domain of the attacker's choosing. This can lead to unauthorized access to internal services, cloud metadata APIs, and internal network scanning.": 'SSRF آسیب‌پذیری‌ای است که باعث می‌شود برنامه سمت سرور درخواست HTTP به مقصد دلخواه مهاجم ارسال کند؛ این موضوع می‌تواند به دسترسی غیرمجاز به سرویس‌های داخلی، متادیتای ابری و اسکن شبکه داخلی منجر شود.',
  'XXE injection is a type of attack against an application that parses XML input. It occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser. XXE can lead to disclosure of confidential data, SSRF, port scanning, and RCE.': 'XXE حمله‌ای علیه برنامه‌هایی است که ورودی XML را پردازش می‌کنند. وقتی موجودیت خارجی توسط parser ضعیف پردازش شود، ممکن است افشای داده، SSRF، اسکن پورت یا اجرای کد رخ دهد.',

  'Path Traversal': '?????? ????',
  'Command Injection': '????? ?????',
  'Open Redirect': '????? ???? ??? ?????',
  'SQLi Cheat Sheet': '???? ???? SQLi',
  'XSS Cheat Sheet': '???? ???? XSS',
  'SSRF Targets': '??????? SSRF',
  'JWT Attacks': '???????? JWT',
  'Passive recon: OSINT, Shodan, Censys, Google Dorks': '??????? ???????: OSINT? Shodan? Censys ? Google Dorks',
  'Active recon: Nmap, Masscan port scanning': '??????? ????: ???? ???? ?? Nmap ? Masscan',
  'Subdomain enumeration: Subfinder, Amass, Assetfinder': '????? ????????: Subfinder? Amass ? Assetfinder',
  'Directory/file discovery: Feroxbuster, Gobuster, ffuf': '??? ?????????/????: Feroxbuster? Gobuster ? ffuf',
  'Technology fingerprinting: Wappalyzer, WhatWeb': '??? ????? ??????: Wappalyzer ? WhatWeb',
  'GitHub recon: secrets in source code, API keys': '??????? GitHub: ????? ?? ?? ???? ? ??????? API',
  'DNS enumeration: Zone transfers, DNSX': '????? DNS: ?????? Zone ? DNSX',
  'Parameter discovery with Arjun or Burp Param Miner': '??? ??????? ?? Arjun ?? Burp Param Miner',
  'API endpoint discovery via Swagger, Postman collections': '??? endpoint??? API ?? Swagger ? ?????????? Postman',
  'Authentication mechanism analysis (JWT, OAuth, sessions)': '????? ??????? ????? ???? (JWT? OAuth ? ???????)',
  'WAF detection and fingerprinting': '????? ? ???????? WAF',
  'Business logic mapping: user flows, permissions': '??????????? ???? ????????: ????????? ????? ? ??????',
  'Source code review (if available): leaked JS, secrets': '??????? ?? ???? ?? ???? ??????: JS ???????? ? ?????',
  'OWASP Top 10 testing methodology': '????????? ??? OWASP Top 10',
  'Injection testing: SQLi, XSS, SSTI, XXE, SSRF, NoSQLi': '??? ?????: SQLi? XSS? SSTI? XXE? SSRF ? NoSQLi',
  'Authentication bypass: default creds, brute force, JWT attacks': '??? ??? ????? ????: ?????????? ???????? brute force ? ???????? JWT',
  'Authorization testing: IDOR, privilege escalation, path traversal': '??? ???????: IDOR? ?????? ??? ?????? ? ?????? ????',
  'Business logic: negative values, workflow bypasses, race conditions': '???? ????????: ?????? ????? ??? ??? ????? ??? ? race condition',
  'Client-side attacks: CSRF, Clickjacking, XSS via DOM': '???????? ??? ?????: CSRF? Clickjacking ? XSS ?? ???? DOM',
  'Demonstrate impact: data exfiltration, account takeover PoC': '????? ???: ???? ???? ? PoC ????? ????',
  'Internal network pivoting (if in scope)': 'Pivot ?? ???? ????? ?? ???? ???? ???? ??????',
  'Sensitive data access demonstration': '????? ?????? ?? ???????? ????',
  'Screenshot evidence and request/response capture': '????? ?????? ? ??? ???????/????',
  'Impact severity assessment using CVSS': '??????? ??? ??? ?? CVSS',
  'Clear vulnerability title with CWE reference': '????? ???? ?????????? ????? ?? ???? CWE',
  'Severity rating with CVSS v3.1 score': '????????? ??? ?? ?????? CVSS v3.1',
  'Step-by-step reproduction instructions': '?????????? ???????? ??????????????',
  'Impact description (what attacker can do)': '????? ???? ????? ?? ???? ???????? ????? ???',
  'Screenshots, HTTP requests, video PoC': '??????????? ??????????? HTTP ? ?????? PoC',
  'Remediation recommendations with code examples': '?????????? ????? ????? ?? ????? ??',
  'PortSwigger Web Academy': '?????? ?? PortSwigger',
  'Free web security training labs': '????????????? ?????? ????? ????? ??',
  'OWASP Testing Guide': '??????? ??? OWASP',
  'Comprehensive web security testing methodology': '????????? ???? ??? ????? ??',
  HackTricks: 'HackTricks',
  'CTF and penetration testing tricks': '???????? CTF ? ??? ????',
  PayloadsAllTheThings: 'PayloadsAllTheThings',
  'Huge list of security payloads': '????? ???? payload??? ??????',
  'Bug Bounty Tips': '???????? ?????????',
  'Community bug bounty tips and tricks': '??????? ? ???????? ????? ?????????',
  SecLists: 'SecLists',
  'Security-focused wordlists': 'Wordlist??? ?????? ?? ?????',
  'Remote Code Execution vulnerabilities allow attackers to run arbitrary code on the target server. RCE can occur through command injection, deserialization flaws, file inclusion, template injection, or exploiting vulnerable software components.': 'آسیب‌پذیری اجرای کد از راه دور به مهاجم اجازه می‌دهد کد دلخواه را روی سرور هدف اجرا کند. RCE می‌تواند از تزریق فرمان، deserialization، file inclusion، تزریق قالب یا اجزای آسیب‌پذیر ایجاد شود.',
};

const faOverrides: Record<string, string> = {
  'Path Traversal': 'پیمایش مسیر',
  'Command Injection': 'تزریق فرمان',
  'Open Redirect': 'تغییر مسیر باز',
  'SQLi Cheat Sheet': 'برگه تقلب SQLi',
  'XSS Cheat Sheet': 'برگه تقلب XSS',
  'SSRF Targets': 'اهداف SSRF',
  'JWT Attacks': 'حمله‌های JWT',
  'Passive recon: OSINT, Shodan, Censys, Google Dorks': 'شناسایی غیرفعال: OSINT، Shodan، Censys و Google Dorks',
  'Active recon: Nmap, Masscan port scanning': 'شناسایی فعال: اسکن پورت با Nmap و Masscan',
  'Subdomain enumeration: Subfinder, Amass, Assetfinder': 'شمارش زیردامنه: Subfinder، Amass و Assetfinder',
  'Directory/file discovery: Feroxbuster, Gobuster, ffuf': 'کشف دایرکتوری و فایل: Feroxbuster، Gobuster و ffuf',
  'Technology fingerprinting: Wappalyzer, WhatWeb': 'اثر انگشت فناوری: Wappalyzer و WhatWeb',
  'GitHub recon: secrets in source code, API keys': 'شناسایی GitHub: اسرار در کد منبع و کلیدهای API',
  'DNS enumeration: Zone transfers, DNSX': 'شمارش DNS: انتقال Zone و DNSX',
  'Parameter discovery with Arjun or Burp Param Miner': 'کشف پارامتر با Arjun یا Burp Param Miner',
  'API endpoint discovery via Swagger, Postman collections': 'کشف endpointهای API با Swagger و مجموعه‌های Postman',
  'Authentication mechanism analysis (JWT, OAuth, sessions)': 'تحلیل سازوکار احراز هویت (JWT، OAuth و نشست‌ها)',
  'WAF detection and fingerprinting': 'تشخیص و اثرانگشت WAF',
  'Business logic mapping: user flows, permissions': 'نقشه‌برداری منطق کسب‌وکار: جریان‌های کاربر و مجوزها',
  'Source code review (if available): leaked JS, secrets': 'بازبینی کد منبع در صورت دسترسی: JS نشت‌کرده و اسرار',
  'OWASP Top 10 testing methodology': 'روش‌شناسی تست OWASP Top 10',
  'Injection testing: SQLi, XSS, SSTI, XXE, SSRF, NoSQLi': 'تست تزریق: SQLi، XSS، SSTI، XXE، SSRF و NoSQLi',
  'Authentication bypass: default creds, brute force, JWT attacks': 'دور زدن احراز هویت: اعتبارنامه پیش‌فرض، brute force و حمله‌های JWT',
  'Authorization testing: IDOR, privilege escalation, path traversal': 'تست مجوزدهی: IDOR، ارتقای سطح دسترسی و پیمایش مسیر',
  'Business logic: negative values, workflow bypasses, race conditions': 'منطق کسب‌وکار: مقادیر منفی، دور زدن جریان کار و race condition',
  'Client-side attacks: CSRF, Clickjacking, XSS via DOM': 'حمله‌های سمت کاربر: CSRF، Clickjacking و XSS از طریق DOM',
  'Demonstrate impact: data exfiltration, account takeover PoC': 'نمایش اثر: خروج داده و PoC تصاحب حساب',
  'Internal network pivoting (if in scope)': 'Pivot در شبکه داخلی در صورت مجاز بودن محدوده',
  'Sensitive data access demonstration': 'نمایش دسترسی به داده‌های حساس',
  'Screenshot evidence and request/response capture': 'شواهد تصویری و ثبت درخواست و پاسخ',
  'Impact severity assessment using CVSS': 'ارزیابی شدت اثر با CVSS',
  'Clear vulnerability title with CWE reference': 'عنوان واضح آسیب‌پذیری همراه با مرجع CWE',
  'Severity rating with CVSS v3.1 score': 'درجه‌بندی شدت با امتیاز CVSS v3.1',
  'Step-by-step reproduction instructions': 'دستورالعمل بازتولید مرحله‌به‌مرحله',
  'Impact description (what attacker can do)': 'توضیح اثر؛ مهاجم چه کاری می‌تواند انجام دهد',
  'Screenshots, HTTP requests, video PoC': 'اسکرین‌شات، درخواست‌های HTTP و ویدیوی PoC',
  'Remediation recommendations with code examples': 'پیشنهادهای اصلاح همراه با نمونه کد',
  'PortSwigger Web Academy': 'آکادمی وب PortSwigger',
  'Free web security training labs': 'آزمایشگاه‌های رایگان آموزش امنیت وب',
  'OWASP Testing Guide': 'راهنمای تست OWASP',
  'Comprehensive web security testing methodology': 'روش‌شناسی جامع تست امنیت وب',
  'CTF and penetration testing tricks': 'ترفندهای CTF و تست نفوذ',
  'Huge list of security payloads': 'فهرست بزرگ payloadهای امنیتی',
  'Bug Bounty Tips': 'نکته‌های باگ‌بانتی',
  'Community bug bounty tips and tricks': 'نکته‌ها و ترفندهای جامعه باگ‌بانتی',
  'Security-focused wordlists': 'فهرست‌های واژگان متمرکز بر امنیت',
  'All levels': 'همه سطوح',
  Intermediate: 'متوسط',
  Beginner: 'مبتدی',
  'Information Gathering': 'جمع‌آوری اطلاعات',
  'Fingerprinting and enumeration': 'اثر انگشت‌گیری و شمارش',
  'Configuration Testing': 'تست پیکربندی',
  'Security headers and config flaws': 'هدرهای امنیتی و خطاهای پیکربندی',
  'Identity & Auth Testing': 'تست هویت و احراز هویت',
  'Authentication and session management': 'احراز هویت و مدیریت نشست',
  'Authorization Testing': 'تست مجوزدهی',
  'Access control flaws': 'نقص‌های کنترل دسترسی',
  'Injection Testing': 'تست تزریق',
  'All injection categories': 'همه دسته‌های تزریق',
  'Client-Side Testing': 'تست سمت کاربر',
  'Client-side vulnerabilities': 'آسیب‌پذیری‌های سمت کاربر',
  'Master all OWASP Top 10 2021 vulnerabilities with one lab per category, from injection to SSRF.': 'آسیب‌پذیری‌های OWASP Top 10 2021 را با یک آزمایشگاه برای هر دسته، از تزریق تا SSRF، یاد بگیرید.',
  'Most common OWASP vulnerability': 'رایج‌ترین آسیب‌پذیری OWASP',
  'Weak crypto and JWT attacks': 'رمزنگاری ضعیف و حمله‌های JWT',
  'Business logic flaws': 'نقص‌های منطق کسب‌وکار',
  'Misconfigured security controls': 'کنترل‌های امنیتی پیکربندی‌نشده',
  'Outdated and vulnerable libraries': 'کتابخانه‌های قدیمی و آسیب‌پذیر',
  'Authentication weaknesses': 'ضعف‌های احراز هویت',
  'Deserialization and integrity': 'سریال‌سازی معکوس و یکپارچگی',
  'Insufficient logging and monitoring': 'ثبت رویداد و پایش ناکافی',
  'Master Expert-level vulnerabilities: HTTP Smuggling, Race Conditions, Cache Poisoning, Advanced SSTI, Algorithm Confusion.': 'آسیب‌پذیری‌های سطح حرفه‌ای را یاد بگیرید: HTTP Smuggling، Race Conditions، Cache Poisoning، SSTI پیشرفته و Algorithm Confusion.',
  'Advanced Injection': 'تزریق پیشرفته',
  'Blind, time-based, SSTI to RCE': 'بلایند، مبتنی بر زمان و SSTI تا RCE',
  'JWT Advanced': 'JWT پیشرفته',
  'Algorithm confusion and jwk injection': 'سردرگمی الگوریتم و تزریق JWK',
  'HTTP Desync': 'ناهماهنگی HTTP',
  'CL.TE and TE.CL smuggling': 'اسمگلینگ CL.TE و TE.CL',
  'Cache Attacks': 'حمله‌های کش',
  'Web cache poisoning to XSS': 'مسموم‌سازی کش وب تا XSS',
  'Concurrent request exploitation': 'سوءاستفاده از درخواست‌های هم‌زمان',
  'CSP Bypass': 'دور زدن CSP',
  'Content Security Policy evasion': 'فرار از Content Security Policy',
  Search: 'جستجو',
  'Search labs, vulnerabilities, glossary...': 'در آزمایشگاه‌ها، آسیب‌پذیری‌ها و واژه‌نامه جستجو کنید...',
  '{{count}} results for "{{query}}"': '{{count}} نتیجه برای "{{query}}"',
  'Start typing to search labs, vulnerabilities, and glossary terms': 'برای جستجوی آزمایشگاه‌ها، آسیب‌پذیری‌ها و واژه‌های واژه‌نامه شروع به تایپ کنید',
  Glossary: 'واژه‌نامه',
  'No results found': 'نتیجه‌ای پیدا نشد',
  'Try different keywords': 'کلیدواژه‌های دیگری را امتحان کنید',
  'Educational simulation only — no real requests are made': 'فقط شبیه‌سازی آموزشی است و هیچ درخواست واقعی ارسال نمی‌شود',
  'IDOR Test': 'آزمون IDOR',
  'Change /users/1 to /users/2 and select "IDOR" response': 'مسیر `/users/1` را به `/users/2` تغییر دهید و پاسخ `IDOR` را انتخاب کنید',
  'Auth Header': 'هدر احراز هویت',
  'Remove Authorization header to test unauthenticated access': 'برای تست دسترسی بدون احراز هویت، هدر Authorization را حذف کنید',
  'SQLi Detection': 'تشخیص SQLi',
  "Add ' to parameter values and watch for 500 errors": "به مقادیر پارامتر یک ' اضافه کنید و خطاهای 500 را بررسی کنید",
  'Change Host header to internal IP like 127.0.0.1': 'هدر Host را به یک IP داخلی مثل `127.0.0.1` تغییر دهید',
  'JWT Tampering': 'دستکاری JWT',
  'Modify the Bearer token payload and check if accepted': 'payload توکن Bearer را تغییر دهید و ببینید پذیرفته می‌شود یا نه',
  'Method Override': 'تغییر متد',
  'Change GET to POST/DELETE to test access controls': 'برای تست کنترل‌های دسترسی، GET را به POST یا DELETE تغییر دهید',
  Best: 'بهترین',
  'Start Timer': 'شروع تایمر',
  'Reset Timer': 'بازنشانی تایمر',
  Avg: 'میانگین',
  Completed: 'تکمیل‌شده',
  Total: 'کل',
  'Time Trial Stats': 'آمار زمان‌سنجی',
  'Complete {{count}} more labs to unlock your certificate!': '{{count}} آزمایشگاه دیگر کامل کنید تا گواهی شما باز شود',
  "Complete 50 labs to earn your HackPath Certificate of Achievement. You've completed {{completed}}/50 labs.": 'برای دریافت گواهی موفقیت HackPath باید 50 آزمایشگاه را کامل کنید. شما {{completed}} از 50 آزمایشگاه را کامل کرده‌اید.',
  'Lab already completed! You can still practice.': 'این آزمایشگاه قبلاً تکمیل شده است، اما هنوز می‌توانید تمرین کنید.',
  'PAYLOAD INPUT': 'ورودی Payload',
  'Enter your payload...': 'Payload خود را وارد کنید...',
  Submit: 'ارسال',
  'VULNERABILITY EXPLOITED': 'آسیب‌پذیری با موفقیت بهره‌برداری شد',
  'SERVER RESPONSE': 'پاسخ سرور',
  'XP earned!': 'XP دریافت شد!',
  '2x Weekly Bonus!': 'پاداش هفتگی 2x!',
  'Hide Hints': 'پنهان کردن راهنمایی‌ها',
  'Show Hints ({{count}} available)': 'نمایش راهنمایی‌ها ({{count}} مورد)',
  'Hint {{current}}/{{total}}': 'راهنمایی {{current}} از {{total}}',
  Prev: 'قبلی',
  Next: 'بعدی',
  'Hide Payloads': 'پنهان کردن Payloadها',
  'Show Example Payloads': 'نمایش Payloadهای نمونه',
  'Click a payload to use it:': 'برای استفاده روی یک Payload کلیک کنید:',
  'Lab Marked Complete': 'آزمایشگاه تکمیل شد',
  'Mark as Completed (+{{xp}} XP)': 'علامت‌گذاری به‌عنوان تکمیل‌شده (+{{xp}} XP)',
  payloadsCount: '{{count}} payload',
  'View {{category}} Guide': 'مشاهده راهنمای {{category}}',
  'to Level {{level}}': 'ØªØ§ Ø³Ø·Ø­ {{level}}',
  "Complete 50 labs to earn your HackPath Certificate of Achievement. You've completed {{count}}/50 labs.": 'Ø¨Ø±Ø§ÛŒ Ø¯Ø±ÛŒØ§ÙØª Ú¯ÙˆØ§Ù‡ÛŒ Ù…ÙˆÙÙ‚ÛŒØª HackPath Ø¨Ø§ÛŒØ¯ 50 Ø¢Ø²Ù…Ø§ÛŒØ´Ú¯Ø§Ù‡ Ø±Ø§ Ú©Ø§Ù…Ù„ Ú©Ù†ÛŒØ¯. Ø´Ù…Ø§ {{count}} Ø§Ø² 50 Ø¢Ø²Ù…Ø§ÛŒØ´Ú¯Ø§Ù‡ Ø±Ø§ Ú©Ø§Ù…Ù„ Ú©Ø±Ø¯Ù‡â€ŒØ§ÛŒØ¯.',
  '{{count}} characters • Markdown supported': '{{count}} Ú©Ø§Ø±Ø§Ú©ØªØ± • Markdown Ù¾Ø´ØªÛŒØ¨Ø§Ù†ÛŒ Ù…ÛŒâ€ŒØ´ÙˆØ¯',
  'Save Notes': 'Ø°Ø®ÛŒØ±Ù‡ ÛŒØ§Ø¯Ø¯Ø§Ø´Øªâ€ŒÙ‡Ø§',
  'Saved!': 'Ø°Ø®ÛŒØ±Ù‡ Ø´Ø¯!',
  Status: 'ÙˆØ¶Ø¹ÛŒØª',
  'Not completed': 'ØªÚ©Ù…ÛŒÙ„ Ù†Ø´Ø¯Ù‡',
  'Interactive Lab': 'Ø¢Ø²Ù…Ø§ÛŒØ´Ú¯Ø§Ù‡ ØªØ¹Ø§Ù…Ù„ÛŒ',
  'This is a guided lab. Practice on PortSwigger Web Security Academy or your own vulnerable instance.': 'Ø§ÛŒÙ† ÛŒÚ© Ø¢Ø²Ù…Ø§ÛŒØ´Ú¯Ø§Ù‡ Ø±Ø§Ù‡Ù†Ù…Ø§Ø¯Ø§Ø± Ø§Ø³Øª. Ø¢Ù† Ø±Ø§ Ø¯Ø± PortSwigger Web Security Academy ÛŒØ§ Ø±ÙˆÛŒ Ù†Ù…ÙˆÙ†Ù‡ Ø¢Ø³ÛŒØ¨â€ŒÙ¾Ø°ÛŒØ± Ø®ÙˆØ¯ ØªÙ…Ø±ÛŒÙ† Ú©Ù†ÛŒØ¯.',
  'Path traversal (also known as directory traversal) allows attackers to read files outside the intended directory by manipulating variables that reference files with ../ sequences or absolute paths, potentially exposing sensitive system files.': 'Ù¾ÛŒÙ…Ø§ÛŒØ´ Ù…Ø³ÛŒØ± Ø¨Ù‡ Ù…Ù‡Ø§Ø¬Ù… Ø§Ø¬Ø§Ø²Ù‡ Ù…ÛŒâ€ŒØ¯Ù‡Ø¯ Ø¨Ø§ Ø¯Ø³ØªÚ©Ø§Ø±ÛŒ Ù…Ø³ÛŒØ±Ù‡Ø§ÛŒÛŒ Ú©Ù‡ Ø¨Ù‡ ÙØ§ÛŒÙ„â€ŒÙ‡Ø§ Ø§ØشØ§Ø±Ù‡ Ù…ÛŒâ€ŒÚ©Ù†Ù†Ø¯ØŒ ÙØ§ÛŒÙ„â€ŒÙ‡Ø§ÛŒ Ø¨ÛŒØ±ÙˆÙ† Ø§Ø² Ø´Ø§Ø®Ù‡ Ù…ÙˆØ±Ø¯ Ù†Ø¸Ø± Ø±Ø§ Ø¨Ø®ÙˆØ§Ù†Ø¯ Ùˆ ÙØ§ÛŒÙ„â€ŒÙ‡Ø§ÛŒ Ø­Ø³Ø§Ø³ Ø³ÛŒØ³ØªÙ… Ø±Ø§ Ø§ÙØ´Ø§ Ú©Ù†Ø¯.',
  'Sensitive file disclosure (credentials, config files, source code), potential code execution if combined with file write vulnerabilities.': 'Ø§ÙØ´Ø§ÛŒ ÙØ§ÛŒÙ„â€ŒÙ‡Ø§ÛŒ Ø­Ø³Ø§Ø³ Ù…Ø§Ù†Ù†Ø¯ Ø§Ø¹ØªØ¨Ø§Ø±Ù†Ø§Ù…Ù‡â€ŒÙ‡Ø§ØŒ Ù¾ÛŒÚ©Ø±Ø¨Ù†Ø¯ÛŒ Ùˆ Ú©Ø¯ Ù…Ù†Ø¨Ø¹ØŒ Ùˆ Ø¯Ø± ØªØ±Ú©ÛŒØ¨ Ø¨Ø§ Ø¢Ø³ÛŒØ¨â€ŒÙ¾Ø°ÛŒØ±ÛŒ Ù†ÙˆØ´ØªÙ† ÙØ§ÛŒÙ„ØŒ Ø§Ù…Ú©Ø§Ù† Ø§Ø¬Ø±Ø§ÛŒ Ú©Ø¯.',
  'Use allowlists for permitted files, canonicalize paths before validation, jail the application to a specific directory (chroot), use file permission restrictions.': 'Ø¨Ø±Ø§ÛŒ ÙØ§ÛŒÙ„â€ŒÙ‡Ø§ÛŒ Ù…Ø¬Ø§Ø² Ø§Ø² allowlist Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†ÛŒØ¯ØŒ Ù…Ø³ÛŒØ±Ù‡Ø§ Ø±Ø§ Ù¾ÛŒØ´ Ø§Ø² Ø§Ø¹ØªØ¨Ø§Ø±Ø³Ù†Ø¬ÛŒ canonicalize Ú©Ù†ÛŒØ¯ØŒ Ø¨Ø±Ù†Ø§Ù…Ù‡ Ø±Ø§ Ø¨Ù‡ ÛŒÚ© Ø´Ø§Ø®Ù‡ Ù…Ø´Ø®Øµ Ù…Ø­Ø¯ÙˆØ¯ Ú©Ù†ÛŒØ¯ Ùˆ Ø³Ø·Ø­ Ø¯Ø³ØªØ±Ø³ÛŒ ÙØ§ÛŒÙ„â€ŒÙ‡Ø§ Ø±Ø§ Ú©Ø§Ù‡Ø´ Ø¯Ù‡ÛŒØ¯.',
  'IDOR occurs when an application uses user-controllable input to access objects directly without proper authorization checks. Attackers can bypass access controls by modifying reference values to access unauthorized resources belonging to other users.': 'IDOR Ø²Ù…Ø§Ù†ÛŒ Ø±Ø® Ù…ÛŒâ€ŒØ¯Ù‡Ø¯ Ú©Ù‡ Ø¨Ø±Ù†Ø§Ù…Ù‡ Ø§Ø² ÙˆØ±ÙˆØ¯ÛŒ Ù‚Ø§Ø¨Ù„ Ú©Ù†ØªØ±Ù„ Ú©Ø§Ø±Ø¨Ø± Ø¨Ø±Ø§ÛŒ Ø¯Ø³ØªØ±Ø³ÛŒ Ù…Ø³ØªÙ‚ÛŒÙ… Ø¨Ù‡ Ø´ÛŒØ¡Ù‡Ø§ Ø¨Ø¯ÙˆÙ† Ø§Ø¹Ù…Ø§Ù„ Ú©Ù†ØªØ±Ù„ Ù…Ø¬ÙˆØ² ØµØ­ÛŒØ­ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†Ø¯. Ù…Ù‡Ø§Ø¬Ù… Ø¨Ø§ ØªØºÛŒÛŒØ± Ù…Ø±Ø¬Ø¹â€ŒÙ‡Ø§ Ù…ÛŒâ€ŒØªÙˆØ§Ù†Ø¯ Ø¨Ù‡ Ù…Ù†Ø§Ø¨Ø¹ Ø³Ø§ÛŒØ± Ú©Ø§Ø±Ø¨Ø±Ø§Ù† Ø¯Ø³ØªØ±Ø³ÛŒ ÛŒØ§Ø¨Ø¯.',
  'Unauthorized data access, account takeover, sensitive data exposure, privacy violations, mass data harvesting.': 'Ø¯Ø³ØªØ±Ø³ÛŒ ØºÛŒØ±Ù…Ø¬Ø§Ø² Ø¨Ù‡ Ø¯Ø§Ø¯Ù‡ØŒ ØªØµØ§Ø­Ø¨ Ø­Ø³Ø§Ø¨ØŒ Ø§ÙØ´Ø§ÛŒ Ø§Ø·Ù„Ø§Ø¹Ø§Øª Ø­Ø³Ø§Ø³ØŒ Ù†Ù‚Ø¶ Ø­Ø±ÛŒÙ… Ø®ØµÙˆØµÛŒ Ùˆ Ú¯Ø±Ø¯Ø¢ÙˆØ±ÛŒ Ø§Ù†Ø¨ÙˆÙ‡ Ø¯Ø§Ø¯Ù‡.',
  'Implement proper access control checks for every object access, use indirect references (hashed/random IDs), use UUIDs instead of sequential IDs, log and monitor access attempts.': 'Ø¨Ø±Ø§ÛŒ Ù‡Ø± Ø¯Ø³ØªØ±Ø³ÛŒ Ø¨Ù‡ Ø´ÛŒØ¡ Ú©Ù†ØªØ±Ù„ Ù…Ø¬ÙˆØ² ØµØ­ÛŒØ­ Ø§Ø¬Ø±Ø§ Ú©Ù†ÛŒØ¯ØŒ Ø§Ø² Ø§Ø±Ø¬Ø§Ø¹â€ŒÙ‡Ø§ÛŒ ØºÛŒØ±Ù…Ø³ØªÙ‚ÛŒÙ… Ù…Ø§Ù†Ù†Ø¯ Ø´Ù†Ø§Ø³Ù‡â€ŒÙ‡Ø§ÛŒ ØªØµØ§Ø¯ÙÛŒ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†ÛŒØ¯ØŒ UUID Ø±Ø§ Ø¬Ø§ÛŒÚ¯Ø²ÛŒÙ† Ø´Ù†Ø§Ø³Ù‡â€ŒÙ‡Ø§ÛŒ ØªØ±ØªÛŒØ¨ÛŒ Ú©Ù†ÛŒØ¯ Ùˆ ØªÙ„Ø§Ø´â€ŒÙ‡Ø§ÛŒ Ø¯Ø³ØªØ±Ø³ÛŒ Ø±Ø§ Ø«Ø¨Øª Ùˆ Ù¾Ø§ÛŒØ´ Ú©Ù†ÛŒØ¯.',
  'JSON Web Token (JWT) vulnerabilities arise from improper implementation or configuration of JWTs. Common issues include the "none" algorithm attack, algorithm confusion (RS256→HS256), weak secrets, lack of expiration, and sensitive data in payload.': 'Ø¢Ø³ÛŒØ¨â€ŒÙ¾Ø°ÛŒØ±ÛŒâ€ŒÙ‡Ø§ÛŒ JWT Ø¯Ø± Ø§Ø«Ø± Ù¾ÛŒØ§Ø¯Ù‡â€ŒØ³Ø§Ø²ÛŒ ÛŒØ§ Ù¾ÛŒÚ©Ø±Ø¨Ù†Ø¯ÛŒ Ù†Ø§Ø¯Ø±Ø³Øª Ø§ÛŒØ¬Ø§Ø¯ Ù…ÛŒâ€ŒØ´ÙˆÙ†Ø¯. Ù…Ø´Ú©Ù„Ø§Øª Ø±Ø§ÛŒØ¬ Ø´Ø§Ù…Ù„ Ø­Ù…Ù„Ù‡ alg:noneØŒ Ø³Ø±Ø¯Ø±Ú¯Ù…ÛŒ Ø§Ù„Ú¯ÙˆØ±ÛŒØªÙ…ØŒ Ø±Ù…Ø²Ù‡Ø§ÛŒ Ø¶Ø¹ÛŒÙØŒ Ù†Ø¯Ø§Ø´ØªÙ† Ø§Ù†Ù‚Ø¶Ø§ Ùˆ Ø¯Ø§Ø¯Ù‡â€ŒÙ‡Ø§ÛŒ Ø­Ø³Ø§Ø³ Ø¯Ø± payload Ø§Ø³Øª.',
  'Authentication bypass, privilege escalation, account takeover, session hijacking, impersonation of any user including admin.': 'Ø¯ÙˆØ± Ø²Ø¯Ù† Ø§Ø­Ø±Ø§Ø² Ù‡ÙˆÛŒØªØŒ Ø§Ø±ØªÙ‚Ø§ÛŒ Ø³Ø·Ø­ Ø¯Ø³ØªØ±Ø³ÛŒØŒ ØªØµØ§Ø­Ø¨ Ø­Ø³Ø§Ø¨ØŒ Ø±Ø¨ÙˆØ¯Ù† Ù†Ø´Ø³Øª Ùˆ Ø¬Ø§ Ø²Ø¯Ù† Ø¨Ù‡ Ø¬Ø§ÛŒ Ù‡Ø± Ú©Ø§Ø±Ø¨Ø± Ø§Ø² Ø¬Ù…Ù„Ù‡ Ù…Ø¯ÛŒØ±.',
  'Use strong, random secrets, explicitly specify allowed algorithms, validate all claims (exp, iss, aud), use RS256 instead of HS256 for distributed systems, never trust client-supplied algorithm headers.': 'Ø§Ø² Ø±Ù…Ø²Ù‡Ø§ÛŒ Ù‚ÙˆÛŒ Ùˆ ØªØµØ§Ø¯ÙÛŒ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†ÛŒØ¯ØŒ Ø§Ù„Ú¯ÙˆØ±ÛŒØªÙ…â€ŒÙ‡Ø§ÛŒ Ù…Ø¬Ø§Ø² Ø±Ø§ Ø¨Ù‡â€ŒØµØ±Ø§Ø­Øª Ù…Ø´Ø®Øµ Ú©Ù†ÛŒØ¯ØŒ ØªÙ…Ø§Ù… claimÙ‡Ø§ Ø±Ø§ Ø§Ø¹ØªØ¨Ø§Ø±Ø³Ù†Ø¬ÛŒ Ú©Ù†ÛŒØ¯ Ùˆ Ø¨Ù‡ Ù‡Ø¯Ø± Ø§Ù„Ú¯ÙˆØ±ÛŒØªÙ… Ø§Ø±Ø³Ø§Ù„ÛŒ Ø§Ø² Ø³Ù…Øª Ú©Ù„Ø§ÛŒÙ†Øª Ø§Ø¹ØªÙ…Ø§Ø¯ Ù†Ú©Ù†ÛŒØ¯.',
  'Cross-Origin Resource Sharing (CORS) misconfigurations allow malicious websites to make cross-origin requests to APIs on behalf of authenticated users. When origins are trusted too broadly or dynamically without validation, attackers can read sensitive data across origins.': 'Ù¾ÛŒÚ©Ø±Ø¨Ù†Ø¯ÛŒ Ù†Ø§Ø¯Ø±Ø³Øª CORS Ø¨Ù‡ ÙˆØ¨â€ŒØ³Ø§ÛŒØªâ€ŒÙ‡Ø§ÛŒ Ù…Ø®Ø±Ø¨ Ø§Ø¬Ø§Ø²Ù‡ Ù…ÛŒâ€ŒØ¯Ù‡Ø¯ Ø§Ø² Ø·Ø±Ù Ú©Ø§Ø±Ø¨Ø±Ø§Ù† Ø§Ø­Ø±Ø§Ø² Ù‡ÙˆÛŒØªâ€ŒØ´Ø¯Ù‡ Ø¨Ù‡ APIÙ‡Ø§ Ø¯Ø±Ø®ÙˆØ§Ø³Øª Ø¨ÙØ±Ø³ØªÙ†Ø¯. Ø²Ù…Ø§Ù†ÛŒ Ú©Ù‡ originÙ‡Ø§ Ø¨Ø¯ÙˆÙ† Ø§Ø¹ØªØ¨Ø§Ø±Ø³Ù†Ø¬ÛŒ Ø¨Ù‡â€ŒØ´Ú©Ù„ÛŒ Ø¨ÛŒØ´ Ø§Ø² Ø­Ø¯ ÛŒØ§ Ø¯ÛŒÙ†Ø§Ù…ÛŒÚ© Ù…ÙˆØ±Ø¯ Ø§Ø¹ØªÙ…Ø§Ø¯ Ù‚Ø±Ø§Ø± Ù…ÛŒâ€ŒÚ¯ÛŒØ±Ù†Ø¯ØŒ Ù…Ù‡Ø§Ø¬Ù… Ù…ÛŒâ€ŒØªÙˆØ§Ù†Ø¯ Ø¯Ø§Ø¯Ù‡ Ø­Ø³Ø§Ø³ Ø±Ø§ Ø¨ÛŒÙ† originÙ‡Ø§ Ø¨Ø®ÙˆØ§Ù†Ø¯.',
  'Sensitive data theft, authentication token exfiltration, account takeover, API data exposure.': 'Ø³Ø±Ù‚Øª Ø¯Ø§Ø¯Ù‡â€ŒÙ‡Ø§ÛŒ Ø­Ø³Ø§Ø³ØŒ Ø®Ø±ÙˆØ¬ ØªÙˆÚ©Ù†â€ŒÙ‡Ø§ÛŒ Ø§Ø­Ø±Ø§Ø² Ù‡ÙˆÛŒØªØŒ ØªØµØ§Ø­Ø¨ Ø­Ø³Ø§Ø¨ Ùˆ Ø§ÙØ´Ø§ÛŒ Ø¯Ø§Ø¯Ù‡â€ŒÙ‡Ø§ÛŒ API.',
  'Strictly allowlist trusted origins, never use wildcards with credentials, validate Origin headers with exact matching, avoid reflecting Origin header without validation.': 'ÙÙ‚Ø· originÙ‡Ø§ÛŒ Ù…ÙˆØ±Ø¯ Ø§Ø¹ØªÙ…Ø§Ø¯ Ø±Ø§ Ø¨Ù‡â€ŒØµÙˆØ±Øª Ø¯Ù‚ÛŒÙ‚ allowlist Ú©Ù†ÛŒØ¯ØŒ Ù‡Ø±Ú¯Ø² wildcard Ø±Ø§ Ø¨Ø§ credentials Ø¨Ù‡ Ú©Ø§Ø± Ù†Ø¨Ø±ÛŒØ¯ØŒ Ù‡Ø¯Ø± Origin Ø±Ø§ Ø¨Ù‡â€ŒØµÙˆØ±Øª Ø¯Ù‚ÛŒÙ‚ Ø§Ø¹ØªØ¨Ø§Ø±Ø³Ù†Ø¬ÛŒ Ú©Ù†ÛŒØ¯ Ùˆ Ø§Ø² Ø¨Ø§Ø²ØªØ§Ø¨ Origin Ø¨Ø¯ÙˆÙ† Ø¨Ø±Ø±Ø³ÛŒ Ø®ÙˆØ¯Ø¯Ø§Ø±ÛŒ Ú©Ù†ÛŒØ¯.',
  'SSTI occurs when user input is embedded in a template unsafely, allowing attackers to inject template directives. Depending on the template engine, this can lead to information disclosure, file system access, and remote code execution.': 'SSTI Ø²Ù…Ø§Ù†ÛŒ Ø±Ø® Ù…ÛŒâ€ŒØ¯Ù‡Ø¯ Ú©Ù‡ ÙˆØ±ÙˆØ¯ÛŒ Ú©Ø§Ø±Ø¨Ø± Ø¨Ù‡â€ŒØ´Ú©Ù„ÛŒ Ù†Ø§Ø§ÛŒÙ…Ù† Ø¯Ø± template Ù‚Ø±Ø§Ø± Ú¯ÛŒØ±Ø¯ Ùˆ Ø§Ø¬Ø§Ø²Ù‡ ØªØ²Ø±ÛŒÙ‚ Ø¯Ø³ØªÙˆØ±Ø§Øª template Ø±Ø§ Ø¨Ø¯Ù‡Ø¯. Ø¨Ø³ØªÙ‡ Ø¨Ù‡ template engineØŒ Ø§ÛŒÙ† Ù…ÙˆØ¶ÙˆØ¹ Ù…ÛŒâ€ŒØªÙˆØ§Ù†Ø¯ Ø¨Ù‡ Ø§ÙØ´Ø§ÛŒ Ø§Ø·Ù„Ø§Ø¹Ø§ØªØŒ Ø¯Ø³ØªØ±Ø³ÛŒ Ø¨Ù‡ ÙØ§ÛŒÙ„ Ø³ÛŒØ³ØªÙ… Ùˆ Ø§Ø¬Ø±Ø§ÛŒ Ú©Ø¯ Ù…Ù†Ø¬Ø± Ø´ÙˆØ¯.',
  'Remote code execution, file system access, internal service access, sensitive data exfiltration, complete server compromise.': 'Ø§Ø¬Ø±Ø§ÛŒ Ú©Ø¯ Ø§Ø² Ø±Ø§Ù‡ Ø¯ÙˆØ±ØŒ Ø¯Ø³ØªØ±Ø³ÛŒ Ø¨Ù‡ ÙØ§ÛŒÙ„ Ø³ÛŒØ³ØªÙ…ØŒ Ø³Ø±ÙˆÛŒØ³â€ŒÙ‡Ø§ÛŒ Ø¯Ø§Ø®Ù„ÛŒØŒ Ø®Ø±ÙˆØ¬ Ø¯Ø§Ø¯Ù‡â€ŒÙ‡Ø§ÛŒ Ø­Ø³Ø§Ø³ Ùˆ ØªØ³Ø®ÛŒØ± Ú©Ø§Ù…Ù„ Ø³Ø±ÙˆØ±.',
  'Never allow users to control template content, use sandboxed template engines, sanitize and escape all user input before template rendering, use logic-less templates where possible.': 'Ù‡Ø±Ú¯Ø² Ø¨Ù‡ Ú©Ø§Ø±Ø¨Ø± Ø§Ø¬Ø§Ø²Ù‡ Ù†Ø¯Ù‡ÛŒØ¯ Ù…Ø­ØªÙˆØ§ÛŒ template Ø±Ø§ Ú©Ù†ØªØ±Ù„ Ú©Ù†Ø¯ØŒ Ø§Ø² template engineÙ‡Ø§ÛŒ sandboxed Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†ÛŒØ¯ Ùˆ Ù¾ÛŒØ´ Ø§Ø² render ØªÙ…Ø§Ù… ÙˆØ±ÙˆØ¯ÛŒâ€ŒÙ‡Ø§ Ø±Ø§ Ù¾Ø§Ú©â€ŒØ³Ø§Ø²ÛŒ Ùˆ escape Ú©Ù†ÛŒØ¯.',
  'Clickjacking is an interface-based attack where users are tricked into clicking on actionable content on a hidden website. Attackers overlay a transparent iframe over a legitimate site, hijacking user clicks for malicious purposes.': 'Clickjacking ÛŒÚ© Ø­Ù…Ù„Ù‡ Ù…Ø¨ØªÙ†ÛŒ Ø¨Ø± Ø±Ø§Ø¨Ø· Ú©Ø§Ø±Ø¨Ø±ÛŒ Ø§Ø³Øª Ú©Ù‡ Ø¯Ø± Ø¢Ù† Ú©Ø§Ø±Ø¨Ø± ÙØ±ÛŒØ¨ Ù…ÛŒâ€ŒØ®ÙˆØ±Ø¯ ØªØ§ Ø±ÙˆÛŒ Ù…Ø­ØªÙˆØ§ÛŒ Ø¹Ù…Ù„ÛŒØ§ØªÛŒ Ù…Ø®ÙÛŒ Ú©Ù„ÛŒÚ© Ú©Ù†Ø¯. Ù…Ù‡Ø§Ø¬Ù… Ø¨Ø§ Ù‚Ø±Ø§Ø± Ø¯Ø§Ø¯Ù† iframe Ø´ÙØ§Ù Ø±ÙˆÛŒ ÛŒÚ© Ø³Ø§ÛŒØª Ù…Ø´Ø±ÙˆØ¹ØŒ Ú©Ù„ÛŒÚ©â€ŒÙ‡Ø§ Ø±Ø§ Ø¨Ù‡ Ù…Ù‚Ø§ØµØ¯ Ù…Ø®Ø±Ø¨ Ù…ÛŒâ€ŒØ±Ø¨Ø§ÛŒØ¯.',
  'Unauthorized actions performed by user, social media manipulation, account settings changes, unauthorized purchases, Like/Share hijacking.': 'Ø§Ù†Ø¬Ø§Ù… Ø§Ù‚Ø¯Ø§Ù…Ø§Øª ØºÛŒØ±Ù…Ø¬Ø§Ø² Ø¨Ù‡ Ù†Ø§Ù… Ú©Ø§Ø±Ø¨Ø±ØŒ Ø¯Ø³ØªÚ©Ø§Ø±ÛŒ Ø±Ø³Ø§Ù†Ù‡â€ŒÙ‡Ø§ÛŒ Ø§Ø¬ØªÙ…Ø§Ø¹ÛŒØŒ ØªØºÛŒÛŒØ± ØªÙ†Ø¸ÛŒÙ…Ø§Øª Ø­Ø³Ø§Ø¨ØŒ Ø®Ø±ÛŒØ¯Ù‡Ø§ÛŒ ØºÛŒØ±Ù…Ø¬Ø§Ø² Ùˆ Ø³ÙˆØ¡Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø§Ø² Like/Share.',
  'Implement X-Frame-Options header (DENY/SAMEORIGIN), use Content Security Policy frame-ancestors directive, implement framebusting JavaScript (defense in depth).': 'Ù‡Ø¯Ø± X-Frame-Options Ø±Ø§ Ø¨Ø§ DENY ÛŒØ§ SAMEORIGIN Ø§Ø¹Ù…Ø§Ù„ Ú©Ù†ÛŒØ¯ØŒ Ø§Ø² frame-ancestors Ø¯Ø± CSP Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†ÛŒØ¯ Ùˆ Ø¨Ù‡â€ŒØ¹Ù†ÙˆØ§Ù† Ù„Ø§ÛŒÙ‡ Ø§Ø¶Ø§ÙÛŒ Ø¯ÙØ§Ø¹ØŒ framebusting JavaScript Ø¯Ø§Ø´ØªÙ‡ Ø¨Ø§Ø´ÛŒØ¯.',
  'NoSQL injection attacks exploit vulnerabilities in applications using NoSQL databases like MongoDB, CouchDB, and Redis. Unlike SQL injection, NoSQL injection uses database-specific query operators and JavaScript execution to manipulate queries.': 'Ø­Ù…Ù„Ù‡â€ŒÙ‡Ø§ÛŒ NoSQL injection Ø§Ø² Ø¢Ø³ÛŒØ¨â€ŒÙ¾Ø°ÛŒØ±ÛŒâ€ŒÙ‡Ø§ÛŒ Ø¨Ø±Ù†Ø§Ù…Ù‡â€ŒÙ‡Ø§ÛŒÛŒ Ú©Ù‡ Ø§Ø² Ù¾Ø§ÛŒÚ¯Ø§Ù‡â€ŒÙ‡Ø§ÛŒ NoSQL Ù…Ø§Ù†Ù†Ø¯ MongoDBØŒ CouchDB Ùˆ Redis Ø§Ø³ØªÙØ§Ø¯Ù‡ Ù…ÛŒâ€ŒÚ©Ù†Ù†Ø¯ Ø³ÙˆØ¡Ø§Ø³ØªÙØ§Ø¯Ù‡ Ù…ÛŒâ€ŒÚ©Ù†Ù†Ø¯. Ø¨Ø±Ø®Ù„Ø§Ù SQL injectionØŒ Ø¯Ø± Ø§ÛŒÙ†Ø¬Ø§ Ø§Ø² operatorÙ‡Ø§ÛŒ Ø®Ø§Øµ Ù¾Ø§ÛŒÚ¯Ø§Ù‡ Ø¯Ø§Ø¯Ù‡ Ùˆ Ø§Ø¬Ø±Ø§ÛŒ JavaScript Ø¨Ø±Ø§ÛŒ Ø¯Ø³ØªÚ©Ø§Ø±ÛŒ Ù¾Ø±Ø³â€ŒÙˆØ¬Ùˆ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ù…ÛŒâ€ŒØ´ÙˆØ¯.',
  'Authentication bypass, data exfiltration, data manipulation, denial of service, in some cases code execution.': 'Ø¯ÙˆØ± Ø²Ø¯Ù† Ø§Ø­Ø±Ø§Ø² Ù‡ÙˆÛŒØªØŒ Ø®Ø±ÙˆØ¬ Ø¯Ø§Ø¯Ù‡ØŒ Ø¯Ø³ØªÚ©Ø§Ø±ÛŒ Ø¯Ø§Ø¯Ù‡ØŒ Ø§ÛŒØ¬Ø§Ø¯ Ø§Ø®ØªÙ„Ø§Ù„ Ø¯Ø± Ø³Ø±ÙˆÛŒØ³ Ùˆ Ø¯Ø± Ø¨Ø±Ø®ÛŒ Ø­Ø§Ù„Øªâ€ŒÙ‡Ø§ Ø§Ø¬Ø±Ø§ÛŒ Ú©Ø¯.',
  'Use query builder libraries, validate and sanitize input types, use schema validation, avoid passing user input directly to query operators, disable JavaScript execution in MongoDB.': 'Ø§Ø² Ú©ØªØ§Ø¨Ø®Ø§Ù†Ù‡â€ŒÙ‡Ø§ÛŒ query builder Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†ÛŒØ¯ØŒ Ù†ÙˆØ¹ ÙˆØ±ÙˆØ¯ÛŒâ€ŒÙ‡Ø§ Ø±Ø§ Ø§Ø¹ØªØ¨Ø§Ø±Ø³Ù†Ø¬ÛŒ Ùˆ Ù¾Ø§Ú©â€ŒØ³Ø§Ø²ÛŒ Ú©Ù†ÛŒØ¯ØŒ Ø§Ø² schema validation Ø¨Ù‡Ø±Ù‡ Ø¨Ø¨Ø±ÛŒØ¯ Ùˆ ÙˆØ±ÙˆØ¯ÛŒ Ú©Ø§Ø±Ø¨Ø± Ø±Ø§ Ù…Ø³ØªÙ‚ÛŒÙ…Ø§Ù‹ Ø¨Ù‡ operatorÙ‡Ø§ÛŒ query Ù†Ø¯Ù‡ÛŒØ¯.',
  'HTTP request smuggling is a technique for interfering with the way a web site processes sequences of HTTP requests received from one or more users. It exploits discrepancies in how front-end and back-end servers parse HTTP request boundaries.': 'HTTP request smuggling Ø±ÙˆØ´ÛŒ Ø¨Ø±Ø§ÛŒ Ø§Ø®ØªÙ„Ø§Ù„ Ø¯Ø± Ø´ÛŒÙˆÙ‡ Ù¾Ø±Ø¯Ø§Ø²Ø´ Ø²Ù†Ø¬ÛŒØ±Ù‡ Ø¯Ø±Ø®ÙˆØ§Ø³Øªâ€ŒÙ‡Ø§ÛŒ HTTP Ø¯Ø± ÛŒÚ© ÙˆØ¨â€ŒØ³Ø§ÛŒØª Ø§Ø³Øª. Ø§ÛŒÙ† Ø­Ù…Ù„Ù‡ Ø§Ø² Ù†Ø§Ù‡Ù…Ø§Ù‡Ù†Ú¯ÛŒ Ø¨ÛŒÙ† Ø³Ø±ÙˆØ±Ù‡Ø§ÛŒ front-end Ùˆ back-end Ø¯Ø± ØªÙØ³ÛŒØ± Ù…Ø±Ø² Ø¯Ø±Ø®ÙˆØ§Ø³Øªâ€ŒÙ‡Ø§ Ø³ÙˆØ¡Ø§Ø³ØªÙØ§Ø¯Ù‡ Ù…ÛŒâ€ŒÚ©Ù†Ø¯.',
  'Bypass security controls, gain unauthorized access to sensitive data, hijack other users\' requests, XSS, cache poisoning, credential capture.': 'Ø¯ÙˆØ± Ø²Ø¯Ù† Ú©Ù†ØªØ±Ù„â€ŒÙ‡Ø§ÛŒ Ø§Ù…Ù†ÛŒØªÛŒØŒ Ø¯Ø³ØªØ±Ø³ÛŒ ØºÛŒØ±Ù…Ø¬Ø§Ø² Ø¨Ù‡ Ø¯Ø§Ø¯Ù‡â€ŒÙ‡Ø§ÛŒ Ø­Ø³Ø§Ø³ØŒ Ø±Ø¨ÙˆØ¯Ù† Ø¯Ø±Ø®ÙˆØ§Ø³Øª Ø³Ø§ÛŒØ± Ú©Ø§Ø±Ø¨Ø±Ø§Ù†ØŒ XSSØŒ cache poisoning Ùˆ Ø¬Ù…Ø¹â€ŒØ¢ÙˆØ±ÛŒ Ø§Ø¹ØªØ¨Ø§Ø±Ù†Ø§Ù…Ù‡.',
  'Use HTTP/2 end-to-end, disable reuse of back-end connections, use consistent parsing between front-end and back-end, disable ambiguous request support.': 'Ø§Ø² HTTP/2 Ø¨Ù‡â€ŒØµÙˆØ±Øª end-to-end Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†ÛŒØ¯ØŒ Ø§Ø² Ø¨Ø§Ø²Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø§ØªØµØ§Ù„Ø§Øª back-end Ø¬Ù„ÙˆÚ¯ÛŒØ±ÛŒ Ú©Ù†ÛŒØ¯ØŒ parsing ÛŒÚ©Ø³Ø§Ù† Ø¨ÛŒÙ† front-end Ùˆ back-end Ø¯Ø§Ø´ØªÙ‡ Ø¨Ø§Ø´ÛŒØ¯ Ùˆ Ù¾Ø´ØªÛŒØ¨Ø§Ù†ÛŒ Ø§Ø² Ø¯Ø±Ø®ÙˆØ§Ø³Øªâ€ŒÙ‡Ø§ÛŒ Ù…Ø¨Ù‡Ù… Ø±Ø§ ØºÛŒØ±ÙØ¹Ø§Ù„ Ú©Ù†ÛŒØ¯.',
  'File upload vulnerabilities occur when a web server allows users to upload files without sufficiently validating properties like name, type, contents, or size. Improper handling can lead to RCE, XSS, or other serious attacks.': 'Ø¢Ø³ÛŒØ¨â€ŒÙ¾Ø°ÛŒØ±ÛŒâ€ŒÙ‡Ø§ÛŒ File Upload Ø²Ù…Ø§Ù†ÛŒ Ø±Ø® Ù…ÛŒâ€ŒØ¯Ù‡Ù†Ø¯ Ú©Ù‡ Ø³Ø±ÙˆØ± ÙˆØ¨ Ø¨Ù‡ Ú©Ø§Ø±Ø¨Ø±Ø§Ù† Ø§Ø¬Ø§Ø²Ù‡ Ø¨Ø§Ø±Ú¯Ø°Ø§Ø±ÛŒ ÙØ§ÛŒÙ„ Ø±Ø§ Ø¨Ø¯ÙˆÙ† Ø§Ø¹ØªØ¨Ø§Ø±Ø³Ù†Ø¬ÛŒ Ú©Ø§ÙÛŒ Ù†Ø§Ù…ØŒ Ù†ÙˆØ¹ØŒ Ù…Ø­ØªÙˆØ§ ÛŒØ§ Ø§Ù†Ø¯Ø§Ø²Ù‡ Ù…ÛŒâ€ŒØ¯Ù‡Ø¯. Ù…Ø¯ÛŒØ±ÛŒØª Ù†Ø§Ø¯Ø±Ø³Øª Ø¢Ù† Ù…ÛŒâ€ŒØªÙˆØ§Ù†Ø¯ Ø¨Ù‡ RCEØŒ XSS ÛŒØ§ Ø­Ù…Ù„Ø§Øª Ø¬Ø¯ÛŒ Ø¯ÛŒÚ¯Ø± Ù…Ù†Ø¬Ø± Ø´ÙˆØ¯.',
  'Remote code execution, XSS via malicious SVG/HTML, DoS via zip bombs, phishing via malicious documents, server compromise.': 'Ø§Ø¬Ø±Ø§ÛŒ Ú©Ø¯ Ø§Ø² Ø±Ø§Ù‡ Ø¯ÙˆØ±ØŒ XSS Ø§Ø² Ø·Ø±ÛŒÙ‚ SVG/HTML Ù…Ø®Ø±Ø¨ØŒ DoS Ø¨Ø§ zip bombØŒ ÙÛŒØ´ÛŒÙ†Ú¯ Ø¨Ø§ Ø§Ø³Ù†Ø§Ø¯ Ù…Ø®Ø±Ø¨ Ùˆ ØªØ³Ø®ÛŒØ± Ø³Ø±ÙˆØ±.',
  'Validate file type by content (magic bytes), use allowlist for permitted types, rename uploaded files, store outside web root, scan with antivirus, use separate domain for user content.': 'Ù†ÙˆØ¹ ÙØ§ÛŒÙ„ Ø±Ø§ Ø¨Ø§ Ø¨Ø±Ø±Ø³ÛŒ Ù…Ø­ØªÙˆØ§ Ùˆ magic byte Ø§Ø¹ØªØ¨Ø§Ø±Ø³Ù†Ø¬ÛŒ Ú©Ù†ÛŒØ¯ØŒ Ø§Ø² allowlist Ø¨Ø±Ø§ÛŒ ÙØ§ÛŒÙ„â€ŒÙ‡Ø§ÛŒ Ù…Ø¬Ø§Ø² Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†ÛŒØ¯ØŒ ÙØ§ÛŒÙ„â€ŒÙ‡Ø§ÛŒ Ø¨Ø§Ø±Ú¯Ø°Ø§Ø±ÛŒâ€ŒØ´Ø¯Ù‡ Ø±Ø§ ØªØºÛŒÛŒØ± Ù†Ø§Ù… Ø¯Ù‡ÛŒØ¯ Ùˆ Ø¯Ø± Ø®Ø§Ø±Ø¬ Ø§Ø² web root Ù†Ú¯Ù‡ Ø¯Ø§Ø±ÛŒ Ú©Ù†ÛŒØ¯.',
  'Insecure deserialization occurs when untrusted data is used to abuse the logic of an application, inflict a denial of service (DoS) attack, or even execute arbitrary code. It is one of the most critical vulnerability classes in modern applications.': 'Deserialization Ù†Ø§Ø§ÛŒÙ…Ù† Ø²Ù…Ø§Ù†ÛŒ Ø±Ø® Ù…ÛŒâ€ŒØ¯Ù‡Ø¯ Ú©Ù‡ Ø§Ø² Ø¯Ø§Ø¯Ù‡â€ŒÙ‡Ø§ÛŒ ØºÛŒØ±Ù…ÙˆØ±Ø¯Ø§Ø¹ØªÙ…Ø§Ø¯ Ø¨Ø±Ø§ÛŒ Ø³ÙˆØ¡Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø§Ø² Ù…Ù†Ø·Ù‚ Ø¨Ø±Ù†Ø§Ù…Ù‡ØŒ Ø§ÛŒØ¬Ø§Ø¯ DoS ÛŒØ§ Ø­ØªÛŒ Ø§Ø¬Ø±Ø§ÛŒ Ú©Ø¯ Ø¯Ù„Ø®ÙˆØ§Ù‡ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø´ÙˆØ¯. Ø§ÛŒÙ† ÛŒÚ©ÛŒ Ø§Ø² Ø­Ø³Ø§Ø³â€ŒØªØ±ÛŒÙ† Ø¯Ø³ØªÙ‡â€ŒÙ‡Ø§ÛŒ Ø¢Ø³ÛŒØ¨â€ŒÙ¾Ø°ÛŒØ±ÛŒ Ø¯Ø± Ø¨Ø±Ù†Ø§Ù…Ù‡â€ŒÙ‡Ø§ÛŒ Ù…Ø¯Ø±Ù† Ø§Ø³Øª.',
  'Avoid deserializing data from untrusted sources, use integrity checks (HMAC) on serialized data, use safe serialization formats (JSON), implement deserialization firewalls.': 'Ø§Ø² deserialize Ú©Ø±Ø¯Ù† Ø¯Ø§Ø¯Ù‡ Ø§Ø² Ù…Ù†Ø§Ø¨Ø¹ ØºÛŒØ±Ù…ÙˆØ±Ø¯Ø§Ø¹ØªÙ…Ø§Ø¯ Ø®ÙˆØ¯Ø¯Ø§Ø±ÛŒ Ú©Ù†ÛŒØ¯ØŒ Ø±ÙˆÛŒ Ø¯Ø§Ø¯Ù‡ serialized Ø¨Ø±Ø±Ø³ÛŒ ÛŒÚ©Ù¾Ø§Ø±Ú†Ú¯ÛŒ Ù…Ø§Ù†Ù†Ø¯ HMAC Ø§Ø¬Ø±Ø§ Ú©Ù†ÛŒØ¯ØŒ Ø§Ø² Ù‚Ø§Ù„Ø¨â€ŒÙ‡Ø§ÛŒ Ø§ÛŒÙ…Ù†â€ŒØªØ± Ù…Ø§Ù†Ù†Ø¯ JSON Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†ÛŒØ¯ Ùˆ Ø¯ÛŒÙˆØ§Ø± Ø¯ÙØ§Ø¹ÛŒ deserialize Ø¯Ø§Ø´ØªÙ‡ Ø¨Ø§Ø´ÛŒØ¯.',
  'GraphQL APIs introduce unique security challenges including introspection-based information disclosure, batching attacks for rate limit bypass, deeply nested queries for DoS, injection via input types, and improper authorization on resolvers.': 'APIÙ‡Ø§ÛŒ GraphQL Ú†Ø§Ù„Ø´â€ŒÙ‡Ø§ÛŒ Ø§Ù…Ù†ÛŒØªÛŒ Ù…Ù†Ø­ØµØ±Ø¨Ù‡â€ŒÙØ±Ø¯ÛŒ Ø±Ø§ Ø§ÛŒØ¬Ø§Ø¯ Ù…ÛŒâ€ŒÚ©Ù†Ù†Ø¯ØŒ Ø§Ø² Ø¬Ù…Ù„Ù‡ Ø§ÙØ´Ø§ÛŒ Ø§Ø·Ù„Ø§Ø¹Ø§Øª Ø¨Ø§ introspectionØŒ Ø¯ÙˆØ± Ø²Ø¯Ù† rate limit Ø¨Ø§ batchingØŒ DoS Ø¨Ø§ queryÙ‡Ø§ÛŒ ØªÙˆØ¯Ø±ØªÙˆ Ùˆ Ù…Ø¬ÙˆØ²Ø¯Ù‡ÛŒ Ù†Ø§Ø¯Ø±Ø³Øª Ø¯Ø± resolverÙ‡Ø§.',
  'Schema disclosure, authentication bypass, DoS via complex queries, authorization bypass, injection attacks, mass data exfiltration.': 'Ø§ÙØ´Ø§ÛŒ schemaØŒ Ø¯ÙˆØ± Ø²Ø¯Ù† Ø§Ø­Ø±Ø§Ø² Ù‡ÙˆÛŒØªØŒ DoS Ø¨Ø§ queryÙ‡Ø§ÛŒ Ù¾ÛŒÚ†ÛŒØ¯Ù‡ØŒ Ø¯ÙˆØ± Ø²Ø¯Ù† Ù…Ø¬ÙˆØ²Ø¯Ù‡ÛŒØŒ Ø­Ù…Ù„Ø§Øª ØªØ²Ø±ÛŒÙ‚ Ùˆ Ø®Ø±ÙˆØ¬ Ø§Ù†Ø¨ÙˆÙ‡ Ø¯Ø§Ø¯Ù‡.',
  'Disable introspection in production, implement query depth limiting, use query cost analysis, apply field-level authorization in resolvers, rate limit queries, validate all inputs.': 'introspection Ø±Ø§ Ø¯Ø± Ù…Ø­ÛŒØ· production ØºÛŒØ±ÙØ¹Ø§Ù„ Ú©Ù†ÛŒØ¯ØŒ Ù…Ø­Ø¯ÙˆØ¯ÛŒØª Ø¹Ù…Ù‚ query Ø§Ø¬Ø±Ø§ Ú©Ù†ÛŒØ¯ØŒ Ø§Ø² ØªØ­Ù„ÛŒÙ„ Ù‡Ø²ÛŒÙ†Ù‡ query Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†ÛŒØ¯ØŒ Ø¯Ø± resolverÙ‡Ø§ Ù…Ø¬ÙˆØ²Ø¯Ù‡ÛŒ Ø¯Ø± Ø³Ø·Ø­ field Ø§Ø¬Ø±Ø§ Ú©Ù†ÛŒØ¯ Ùˆ ØªÙ…Ø§Ù… ÙˆØ±ÙˆØ¯ÛŒâ€ŒÙ‡Ø§ Ø±Ø§ Ø§Ø¹ØªØ¨Ø§Ø±Ø³Ù†Ø¬ÛŒ Ú©Ù†ÛŒØ¯.',
  'OAuth 2.0 implementation flaws can lead to account takeover, unauthorized data access, and privilege escalation. Common issues include CSRF on OAuth flow, open redirectors, state parameter misuse, and authorization code interception.': 'Ù†Ù‚Ø§ÛŒØµ Ø¯Ø± Ù¾ÛŒØ§Ø¯Ù‡â€ŒØ³Ø§Ø²ÛŒ OAuth 2.0 Ù…ÛŒâ€ŒØªÙˆØ§Ù†Ø¯ Ø¨Ù‡ ØªØµØ§Ø­Ø¨ Ø­Ø³Ø§Ø¨ØŒ Ø¯Ø³ØªØ±Ø³ÛŒ ØºÛŒØ±Ù…Ø¬Ø§Ø² Ø¨Ù‡ Ø¯Ø§Ø¯Ù‡ Ùˆ Ø§Ø±ØªÙ‚Ø§ÛŒ Ø³Ø·Ø­ Ø¯Ø³ØªØ±Ø³ÛŒ Ù…Ù†Ø¬Ø± Ø´ÙˆØ¯. Ù…Ø´Ú©Ù„Ø§Øª Ø±Ø§ÛŒØ¬ Ø´Ø§Ù…Ù„ CSRF Ø¯Ø± Ø¬Ø±ÛŒØ§Ù† OAuthØŒ open redirectØŒ Ø³ÙˆØ¡Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø§Ø² state Ùˆ Ø±Ø¨ÙˆØ¯Ù† authorization code Ø§Ø³Øª.',
  'Account takeover, unauthorized data access to third-party resources, privilege escalation, cross-site request forgery on authorization.': 'ØªØµØ§Ø­Ø¨ Ø­Ø³Ø§Ø¨ØŒ Ø¯Ø³ØªØ±Ø³ÛŒ ØºÛŒØ±Ù…Ø¬Ø§Ø² Ø¨Ù‡ Ù…Ù†Ø§Ø¨Ø¹ Ø·Ø±Ù Ø³ÙˆÙ…ØŒ Ø§Ø±ØªÙ‚Ø§ÛŒ Ø³Ø·Ø­ Ø¯Ø³ØªØ±Ø³ÛŒ Ùˆ Ø¬Ø¹Ù„ Ø¯Ø±Ø®ÙˆØ§Ø³Øª Ø¯Ø± ÙØ±Ø¢ÛŒÙ†Ø¯ authorization.',
  'Always use and validate state parameter, use PKCE for public clients, validate redirect URIs strictly, use short-lived authorization codes, implement proper token storage.': 'Ù‡Ù…ÛŒØ´Ù‡ Ø§Ø² state Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†ÛŒØ¯ Ùˆ Ø¢Ù† Ø±Ø§ Ø§Ø¹ØªØ¨Ø§Ø±Ø³Ù†Ø¬ÛŒ Ú©Ù†ÛŒØ¯ØŒ Ø¨Ø±Ø§ÛŒ clientÙ‡Ø§ÛŒ Ø¹Ù…ÙˆÙ…ÛŒ PKCE Ø±Ø§ Ø¨Ù‡ Ú©Ø§Ø± Ø¨Ø¨Ø±ÛŒØ¯ØŒ redirect URIÙ‡Ø§ Ø±Ø§ Ø¯Ù‚ÛŒÙ‚ Ø¨Ø±Ø±Ø³ÛŒ Ú©Ù†ÛŒØ¯ Ùˆ ØªÙˆÚ©Ù†â€ŒÙ‡Ø§ Ø±Ø§ Ø¨Ù‡â€ŒØ´Ú©Ù„ÛŒ Ø§ÛŒÙ…Ù† Ù†Ú¯Ù‡ Ø¯Ø§Ø±ÛŒ Ú©Ù†ÛŒØ¯.',
  'Race conditions occur when the outcome of a web application depends on timing of events, and attackers can manipulate timing to subvert application logic. Modern web apps with concurrent request handling are particularly susceptible.': 'Race condition Ø²Ù…Ø§Ù†ÛŒ Ø±Ø® Ù…ÛŒâ€ŒØ¯Ù‡Ø¯ Ú©Ù‡ Ù†ØªÛŒØ¬Ù‡ Ø±ÙØªØ§Ø± Ø¨Ø±Ù†Ø§Ù…Ù‡ Ø¨Ù‡ Ø²Ù…Ø§Ù†â€ŒØ¨Ù†Ø¯ÛŒ Ø±ÙˆÛŒØ¯Ø§Ø¯Ù‡Ø§ ÙˆØ§Ø¨Ø³ØªÙ‡ Ø¨Ø§Ø´Ø¯ Ùˆ Ù…Ù‡Ø§Ø¬Ù… Ø¨ØªÙˆØ§Ù†Ø¯ Ø¨Ø§ Ø¯Ø³ØªÚ©Ø§Ø±ÛŒ Ø²Ù…Ø§Ù†â€ŒØ¨Ù†Ø¯ÛŒØŒ Ù…Ù†Ø·Ù‚ Ø¨Ø±Ù†Ø§Ù…Ù‡ Ø±Ø§ Ø¯ÙˆØ± Ø¨Ø²Ù†Ø¯. Ø¨Ø±Ù†Ø§Ù…Ù‡â€ŒÙ‡Ø§ÛŒ ÙˆØ¨ Ù…Ø¯Ø±Ù† Ø¨Ø§ Ù¾Ø±Ø¯Ø§Ø²Ø´ Ù‡Ù…â€ŒØ²Ù…Ø§Ù† Ø¯Ø±Ø®ÙˆØ§Ø³Øªâ€ŒÙ‡Ø§ Ø¨ÛŒØ´ØªØ± Ø¯Ø± Ù…Ø¹Ø±Ø¶ Ø¢Ù† Ù‡Ø³ØªÙ†Ø¯.',
  'Double-spending, inventory manipulation, duplicate coupon use, bypassing single-use limits, account balance manipulation.': 'Ø¯ÙˆØ¨Ø§Ø±Ù‡â€ŒØ®Ø±Ø¬ Ø¯Ø§Ø¯Ù†ØŒ Ø¯Ø³ØªÚ©Ø§Ø±ÛŒ Ù…ÙˆØ¬ÙˆØ¯ÛŒØŒ Ø§Ø³ØªÙØ§Ø¯Ù‡ ØªÚ©Ø±Ø§Ø±ÛŒ Ø§Ø² Ú©ÙˆÙ¾Ù†ØŒ Ø¯ÙˆØ± Ø²Ø¯Ù† Ù…Ø­Ø¯ÙˆØ¯ÛŒØªâ€ŒÙ‡Ø§ÛŒ ÛŒÚ©â€ŒØ¨Ø§Ø±Ù…ØµØ±Ù Ùˆ Ø¯Ø³ØªÚ©Ø§Ø±ÛŒ Ù…ÙˆØ¬ÙˆØ¯ÛŒ Ø­Ø³Ø§Ø¨.',
  'Use database transactions with proper isolation levels, implement locking mechanisms, use atomic operations, validate state changes atomically, use idempotency keys.': 'Ø§Ø² transactionÙ‡Ø§ÛŒ Ù¾Ø§ÛŒÚ¯Ø§Ù‡ Ø¯Ø§Ø¯Ù‡ Ø¨Ø§ isolation level Ù…Ù†Ø§Ø³Ø¨ Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†ÛŒØ¯ØŒ locking Ø±Ø§ Ø§Ø¬Ø±Ø§ Ú©Ù†ÛŒØ¯ØŒ Ø¹Ù…Ù„ÛŒØ§Øª atomic Ø¨Ù‡ Ú©Ø§Ø± Ø¨Ø¨Ø±ÛŒØ¯ Ùˆ ØªØºÛŒÛŒØ±Ø§Øª ÙˆØ¶Ø¹ÛŒØª Ø±Ø§ Ø¨Ù‡â€ŒØ´Ú©Ù„ÛŒ atomic Ø¨Ø±Ø±Ø³ÛŒ Ú©Ù†ÛŒØ¯.',
  'Business logic vulnerabilities are flaws in the design and implementation of an application that allow attackers to elicit unintended behavior. Unlike technical vulnerabilities, these exploit the application\'s own intended functionality in unintended ways.': 'Ø¢Ø³ÛŒØ¨â€ŒÙ¾Ø°ÛŒØ±ÛŒâ€ŒÙ‡Ø§ÛŒ Ù…Ù†Ø·Ù‚ Ú©Ø³Ø¨â€ŒÙˆÚ©Ø§Ø± Ø§ÛŒØ±Ø§Ø¯Ù‡Ø§ÛŒÛŒ Ø¯Ø± Ø·Ø±Ø§Ø­ÛŒ Ùˆ Ù¾ÛŒØ§Ø¯Ù‡â€ŒØ³Ø§Ø²ÛŒ Ø¨Ø±Ù†Ø§Ù…Ù‡ Ù‡Ø³ØªÙ†Ø¯ Ú©Ù‡ Ø¨Ù‡ Ù…Ù‡Ø§Ø¬Ù… Ø§Ø¬Ø§Ø²Ù‡ Ù…ÛŒâ€ŒØ¯Ù‡Ù†Ø¯ Ø±ÙØªØ§Ø±ÛŒ ØºÛŒØ±Ù…Ù†ØªØ¸Ø±Ù‡ Ø§ÛŒØ¬Ø§Ø¯ Ú©Ù†Ø¯. Ø§ÛŒÙ† Ø¯Ø³ØªÙ‡ Ø¨Ø±Ø®Ù„Ø§Ù Ù†Ù‚Ø§ÛŒØµ ÙÙ†ÛŒØŒ Ø§Ø² Ú©Ø§Ø±Ú©Ø±Ø¯ Ø¯Ø±Ø³Øª Ø¨Ø±Ù†Ø§Ù…Ù‡ Ø¯Ø± Ø±Ø§Ù‡ÛŒ Ù†Ø§Ø¯Ø±Ø³Øª Ø³ÙˆØ¡Ø§Ø³ØªÙØ§Ø¯Ù‡ Ù…ÛŒâ€ŒÚ©Ù†Ø¯.',
  'Financial loss, data integrity issues, unauthorized access, bypassing security controls, abusing application features for unintended purposes.': 'Ø²ÛŒØ§Ù† Ù…Ø§Ù„ÛŒØŒ Ù…Ø´Ú©Ù„Ø§Øª ÛŒÚ©Ù¾Ø§Ø±Ú†Ú¯ÛŒ Ø¯Ø§Ø¯Ù‡ØŒ Ø¯Ø³ØªØ±Ø³ÛŒ ØºÛŒØ±Ù…Ø¬Ø§Ø²ØŒ Ø¯ÙˆØ± Ø²Ø¯Ù† Ú©Ù†ØªØ±Ù„â€ŒÙ‡Ø§ÛŒ Ø§Ù…Ù†ÛŒØªÛŒ Ùˆ Ø³ÙˆØ¡Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø§Ø² ÙˆÛŒÚ˜Ú¯ÛŒâ€ŒÙ‡Ø§ÛŒ Ø¨Ø±Ù†Ø§Ù…Ù‡ Ø¨Ø±Ø§ÛŒ Ù…Ù‚Ø§ØµØ¯ÛŒ ØºÛŒØ±Ø§Ø² Ù‡Ø¯Ù Ø§ØµÙ„ÛŒ.',
  'Threat model all business processes, implement server-side validation for all business rules, test edge cases and boundary conditions, implement proper state machine validation.': 'Ø¨Ø±Ø§ÛŒ ØªÙ…Ø§Ù… ÙØ±Ø¢ÛŒÙ†Ø¯Ù‡Ø§ÛŒ Ú©Ø³Ø¨â€ŒÙˆÚ©Ø§Ø± threat model Ø§Ù†Ø¬Ø§Ù… Ø¯Ù‡ÛŒØ¯ØŒ Ù‚ÙˆØ§Ø¹Ø¯ Ø¨Ø±Ù†Ø§Ù…Ù‡ Ø±Ø§ Ø¯Ø± Ø³Ù…Øª Ø³Ø±ÙˆØ± Ø§Ø¹ØªØ¨Ø§Ø±Ø³Ù†Ø¬ÛŒ Ú©Ù†ÛŒØ¯ØŒ edge caseÙ‡Ø§ Ùˆ boundary conditionÙ‡Ø§ Ø±Ø§ Ø¢Ø²Ù…Ø§ÛŒØ´ Ú©Ù†ÛŒØ¯ Ùˆ state machine ØµØ­ÛŒØ­ Ø§Ø¬Ø±Ø§ Ú©Ù†ÛŒØ¯.',
  'Web cache poisoning is an attack where an attacker exploits the behavior of a web server and cache to serve a harmful HTTP response to other users. By manipulating cache keys and unkeyed inputs, attackers can inject malicious content into cached responses.': 'Web cache poisoning Ø­Ù…Ù„Ù‡â€ŒØ§ÛŒ Ø§Ø³Øª Ú©Ù‡ Ø¯Ø± Ø¢Ù† Ù…Ù‡Ø§Ø¬Ù… Ø§Ø² Ø±ÙØªØ§Ø± Ø³Ø±ÙˆØ± Ùˆ cache Ø³ÙˆØ¡Ø§Ø³ØªÙØ§Ø¯Ù‡ Ù…ÛŒâ€ŒÚ©Ù†Ø¯ ØªØ§ Ù¾Ø§Ø³Ø® HTTP Ù…Ø®Ø±Ø¨ÛŒ Ø±Ø§ Ø¨Ù‡ Ø³Ø§ÛŒØ± Ú©Ø§Ø±Ø¨Ø±Ø§Ù† Ø§Ø±Ø³Ø§Ù„ Ú©Ù†Ø¯. Ø¨Ø§ Ø¯Ø³ØªÚ©Ø§Ø±ÛŒ cache keyÙ‡Ø§ Ùˆ ÙˆØ±ÙˆØ¯ÛŒâ€ŒÙ‡Ø§ÛŒÛŒ Ú©Ù‡ Ø¯Ø± Ú©Ù„ÛŒØ¯ Ú©Ø´ Ø¯Ø± Ù†Ø¸Ø± Ú¯Ø±ÙØªÙ‡ Ù†Ù…ÛŒâ€ŒØ´ÙˆÙ†Ø¯ØŒ Ù…Ø­ØªÙˆØ§ÛŒ Ù…Ø®Ø±Ø¨ Ø¯Ø± Ù¾Ø§Ø³Ø®â€ŒÙ‡Ø§ÛŒ cacheâ€ŒØ´Ø¯Ù‡ ØªØ²Ø±ÛŒÙ‚ Ù…ÛŒâ€ŒØ´ÙˆØ¯.',
  'Stored XSS affecting all users who receive poisoned cache, denial of service, JavaScript injection, cookie theft.': 'Stored XSS Ø¨Ø± ØªÙ…Ø§Ù… Ú©Ø§Ø±Ø¨Ø±Ø§Ù†ÛŒ Ú©Ù‡ Ù¾Ø§Ø³Ø® cacheâ€ŒØ´Ø¯Ù‡ Ù…Ø³Ù…ÙˆÙ… Ø±Ø§ Ø¯Ø±ÛŒØ§ÙØª Ù…ÛŒâ€ŒÚ©Ù†Ù†Ø¯ØŒ Ø§ÛŒØ¬Ø§Ø¯ Ø§Ø®ØªÙ„Ø§Ù„ Ø¯Ø± Ø³Ø±ÙˆÛŒØ³ØŒ ØªØ²Ø±ÛŒÙ‚ JavaScript Ùˆ Ø³Ø±Ù‚Øª Ú©ÙˆÚ©ÛŒ.',
  'Avoid using unkeyed inputs in responses, configure cache to include all relevant headers in cache keys, use Cache-Control: no-store for sensitive responses, implement cache key normalization.': 'Ø§Ø² Ø§Ø³ØªÙØ§Ø¯Ù‡ Ø§Ø² ÙˆØ±ÙˆØ¯ÛŒâ€ŒÙ‡Ø§ÛŒÛŒ Ú©Ù‡ Ø¯Ø± cache key Ù†ÛŒØ³ØªÙ†Ø¯ Ø¯Ø± Ù¾Ø§Ø³Ø® Ø®ÙˆØ¯Ø¯Ø§Ø±ÛŒ Ú©Ù†ÛŒØ¯ØŒ Ú©Ø´ Ø±Ø§ Ø·ÙˆØ±ÛŒ Ù¾ÛŒÚ©Ø±Ø¨Ù†Ø¯ÛŒ Ú©Ù†ÛŒØ¯ Ú©Ù‡ Ù‡Ø¯Ø±Ù‡Ø§ÛŒ Ù…Ù‡Ù… Ø¯Ø± cache key Ø¨ÛŒØ§ÛŒÙ†Ø¯ØŒ Ø¨Ø±Ø§ÛŒ Ù¾Ø§Ø³Ø®â€ŒÙ‡Ø§ÛŒ Ø­Ø³Ø§Ø³ Ø§Ø² Cache-Control: no-store Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ù†ÛŒØ¯ Ùˆ cache key normalization Ø§Ø¬Ø±Ø§ Ú©Ù†ÛŒØ¯.',
};

Object.assign(faOverrides, {
  'to Level {{level}}': 'تا سطح {{level}}',
  "Complete 50 labs to earn your HackPath Certificate of Achievement. You've completed {{count}}/50 labs.": 'برای دریافت گواهی موفقیت HackPath باید ۵۰ آزمایشگاه را کامل کنید. شما {{count}} از ۵۰ آزمایشگاه را کامل کرده‌اید.',
  '{{count}} characters • Markdown supported': '{{count}} کاراکتر • Markdown پشتیبانی می‌شود',
  'Save Notes': 'ذخیره یادداشت‌ها',
  'Saved!': 'ذخیره شد!',
  Status: 'وضعیت',
  'Not completed': 'تکمیل نشده',
  'Interactive Lab': 'آزمایشگاه تعاملی',
  'This is a guided lab. Practice on PortSwigger Web Security Academy or your own vulnerable instance.': 'این یک آزمایشگاه راهنمادار است. آن را در PortSwigger Web Security Academy یا روی نمونه آسیب‌پذیر خودتان تمرین کنید.',
  'Remote Code Execution vulnerabilities allow attackers to run arbitrary code on the target server. RCE can occur through command injection, deserialization flaws, file inclusion, template injection, or exploiting vulnerable software components.': 'آسیب‌پذیری اجرای کد از راه دور به مهاجم اجازه می‌دهد کد دلخواه را روی سرور هدف اجرا کند. RCE می‌تواند از تزریق فرمان، deserialization، file inclusion، تزریق template یا سوءاستفاده از اجزای آسیب‌پذیر ایجاد شود.',
  'JSON Web Token (JWT) vulnerabilities arise from improper implementation or configuration of JWTs. Common issues include the "none" algorithm attack, algorithm confusion (RS256→HS256), weak secrets, lack of expiration, and sensitive data in payload.': 'آسیب‌پذیری‌های JWT معمولاً از پیاده‌سازی یا پیکربندی نادرست JWT ایجاد می‌شوند. موارد رایج شامل حمله alg:none، سردرگمی الگوریتم، رازهای ضعیف، نبود زمان انقضا و قرار گرفتن داده حساس در payload است.',
  'IDOR occurs when an application uses user-controllable input to access objects directly without proper authorization checks. Attackers can bypass access controls by modifying reference values to access unauthorized resources belonging to other users.': 'IDOR زمانی رخ می‌دهد که برنامه با ورودی قابل کنترل کاربر، بدون بررسی درست مجوز، مستقیم به اشیا دسترسی می‌دهد. مهاجم با تغییر مقدار مرجع می‌تواند کنترل دسترسی را دور بزند و به منابع غیرمجاز متعلق به کاربران دیگر برسد.',
  'Path traversal (also known as directory traversal) allows attackers to read files outside the intended directory by manipulating variables that reference files with ../ sequences or absolute paths, potentially exposing sensitive system files.': 'پیمایش مسیر به مهاجم اجازه می‌دهد با دستکاری مسیرهایی مثل ../ یا مسیرهای مطلق، فایل‌هایی بیرون از پوشه مجاز را بخواند و احتمالاً فایل‌های حساس سیستم را افشا کند.',
  'Clickjacking is an interface-based attack where users are tricked into clicking on actionable content on a hidden website. Attackers overlay a transparent iframe over a legitimate site, hijacking user clicks for malicious purposes.': 'Clickjacking یک حمله مبتنی بر رابط کاربری است که در آن کاربر فریب می‌خورد روی محتوای عملیاتی یک سایت پنهان کلیک کند. مهاجم با قرار دادن iframe شفاف روی سایت معتبر، کلیک‌های کاربر را برای هدف مخرب می‌رباید.',
  'SSTI occurs when user input is embedded in a template unsafely, allowing attackers to inject template directives. Depending on the template engine, this can lead to information disclosure, file system access, and remote code execution.': 'SSTI وقتی رخ می‌دهد که ورودی کاربر به شکل ناایمن داخل template قرار بگیرد و امکان تزریق دستورهای template را بدهد. بسته به template engine، این مشکل می‌تواند به افشای اطلاعات، دسترسی به فایل‌های سیستم و اجرای کد از راه دور منجر شود.',
  'Cross-Origin Resource Sharing (CORS) misconfigurations allow malicious websites to make cross-origin requests to APIs on behalf of authenticated users. When origins are trusted too broadly or dynamically without validation, attackers can read sensitive data across origins.': 'پیکربندی نادرست CORS به سایت‌های مخرب اجازه می‌دهد از طرف کاربران احراز هویت‌شده به APIها درخواست cross-origin بفرستند. وقتی originها بیش از حد یا به شکل پویا و بدون اعتبارسنجی مورد اعتماد قرار بگیرند، مهاجم می‌تواند داده حساس را از origin دیگر بخواند.',
  'File upload vulnerabilities occur when a web server allows users to upload files without sufficiently validating properties like name, type, contents, or size. Improper handling can lead to RCE, XSS, or other serious attacks.': 'آسیب‌پذیری File Upload زمانی رخ می‌دهد که سرور اجازه بارگذاری فایل را بدون اعتبارسنجی کافی نام، نوع، محتوا یا اندازه بدهد. مدیریت نادرست فایل می‌تواند به RCE، XSS یا حمله‌های جدی دیگر منجر شود.',
  'HTTP request smuggling is a technique for interfering with the way a web site processes sequences of HTTP requests received from one or more users. It exploits discrepancies in how front-end and back-end servers parse HTTP request boundaries.': 'HTTP request smuggling روشی برای اختلال در پردازش زنجیره درخواست‌های HTTP است. این حمله از تفاوت تفسیر مرز درخواست‌ها بین سرور front-end و back-end سوءاستفاده می‌کند.',
  'NoSQL injection attacks exploit vulnerabilities in applications using NoSQL databases like MongoDB, CouchDB, and Redis. Unlike SQL injection, NoSQL injection uses database-specific query operators and JavaScript execution to manipulate queries.': 'حمله NoSQL injection از ضعف برنامه‌هایی سوءاستفاده می‌کند که از پایگاه‌های NoSQL مثل MongoDB، CouchDB و Redis استفاده می‌کنند. برخلاف SQL injection، این حمله از operatorهای مخصوص پایگاه داده و گاهی اجرای JavaScript برای دستکاری query استفاده می‌کند.',
  'OAuth 2.0 implementation flaws can lead to account takeover, unauthorized data access, and privilege escalation. Common issues include CSRF on OAuth flow, open redirectors, state parameter misuse, and authorization code interception.': 'نقص‌های پیاده‌سازی OAuth 2.0 می‌توانند به تصاحب حساب، دسترسی غیرمجاز به داده و ارتقای سطح دسترسی منجر شوند. مشکلات رایج شامل CSRF در جریان OAuth، open redirect، استفاده نادرست از state و ربودن authorization code است.',
  'GraphQL APIs introduce unique security challenges including introspection-based information disclosure, batching attacks for rate limit bypass, deeply nested queries for DoS, injection via input types, and improper authorization on resolvers.': 'APIهای GraphQL چالش‌های امنیتی ویژه‌ای دارند؛ از جمله افشای اطلاعات با introspection، دور زدن rate limit با batching، queryهای بسیار تودرتو برای DoS، تزریق از طریق نوع‌های ورودی و مجوزدهی نادرست در resolverها.',
  'Insecure deserialization occurs when untrusted data is used to abuse the logic of an application, inflict a denial of service (DoS) attack, or even execute arbitrary code. It is one of the most critical vulnerability classes in modern applications.': 'Deserialization ناایمن زمانی رخ می‌دهد که داده غیرقابل اعتماد برای سوءاستفاده از منطق برنامه، ایجاد DoS یا حتی اجرای کد دلخواه استفاده شود. این یکی از حساس‌ترین دسته‌های آسیب‌پذیری در برنامه‌های مدرن است.',
  'Web cache poisoning is an attack where an attacker exploits the behavior of a web server and cache to serve a harmful HTTP response to other users. By manipulating cache keys and unkeyed inputs, attackers can inject malicious content into cached responses.': 'Web cache poisoning حمله‌ای است که در آن مهاجم از رفتار سرور و cache سوءاستفاده می‌کند تا پاسخ HTTP مخرب به کاربران دیگر برسد. با دستکاری cache keyها و ورودی‌هایی که در کلید cache لحاظ نشده‌اند، محتوای مخرب وارد پاسخ cache شده می‌شود.',
  'Business logic vulnerabilities are flaws in the design and implementation of an application that allow attackers to elicit unintended behavior. Unlike technical vulnerabilities, these exploit the application\'s own intended functionality in unintended ways.': 'آسیب‌پذیری‌های منطق کسب‌وکار ضعف‌هایی در طراحی و پیاده‌سازی برنامه هستند که رفتار ناخواسته ایجاد می‌کنند. برخلاف ضعف‌های فنی، این موارد از قابلیت‌های عادی برنامه در مسیری غیرمنتظره سوءاستفاده می‌کنند.',
  'Race conditions occur when the outcome of a web application depends on timing of events, and attackers can manipulate timing to subvert application logic. Modern web apps with concurrent request handling are particularly susceptible.': 'Race condition زمانی رخ می‌دهد که نتیجه رفتار برنامه به زمان‌بندی رویدادها وابسته باشد و مهاجم بتواند با دستکاری زمان‌بندی، منطق برنامه را دور بزند. برنامه‌های وب مدرن با پردازش همزمان درخواست‌ها بیشتر در معرض این مشکل هستند.',
  'Sensitive file disclosure (credentials, config files, source code), potential code execution if combined with file write vulnerabilities.': 'افشای فایل‌های حساس مثل اعتبارنامه‌ها، فایل‌های پیکربندی و کد منبع؛ و در صورت ترکیب با آسیب‌پذیری نوشتن فایل، امکان اجرای کد.',
  'Use allowlists for permitted files, canonicalize paths before validation, jail the application to a specific directory (chroot), use file permission restrictions.': 'برای فایل‌های مجاز از allowlist استفاده کنید، مسیرها را پیش از اعتبارسنجی canonicalize کنید، برنامه را به یک شاخه مشخص محدود کنید و سطح دسترسی فایل‌ها را کاهش دهید.',
  'Unauthorized data access, account takeover, sensitive data exposure, privacy violations, mass data harvesting.': 'دسترسی غیرمجاز به داده، تصاحب حساب، افشای اطلاعات حساس، نقض حریم خصوصی و گردآوری انبوه داده.',
  'Implement proper access control checks for every object access, use indirect references (hashed/random IDs), use UUIDs instead of sequential IDs, log and monitor access attempts.': 'برای هر دسترسی به شیء، کنترل مجوز درست اجرا کنید، از ارجاع‌های غیرمستقیم مثل شناسه‌های تصادفی استفاده کنید، UUID را جایگزین شناسه‌های ترتیبی کنید و تلاش‌های دسترسی را ثبت و پایش کنید.',
  'Authentication bypass, privilege escalation, account takeover, session hijacking, impersonation of any user including admin.': 'دور زدن احراز هویت، ارتقای سطح دسترسی، تصاحب حساب، ربودن نشست و جعل هویت هر کاربر از جمله مدیر.',
  'Use strong, random secrets, explicitly specify allowed algorithms, validate all claims (exp, iss, aud), use RS256 instead of HS256 for distributed systems, never trust client-supplied algorithm headers.': 'از رازهای قوی و تصادفی استفاده کنید، الگوریتم‌های مجاز را صریح مشخص کنید، همه claimها مثل exp و iss و aud را اعتبارسنجی کنید و هرگز به هدر الگوریتم ارسالی از سمت کلاینت اعتماد نکنید.',
  'Sensitive data theft, authentication token exfiltration, account takeover, API data exposure.': 'سرقت داده‌های حساس، خروج توکن‌های احراز هویت، تصاحب حساب و افشای داده‌های API.',
  'Strictly allowlist trusted origins, never use wildcards with credentials, validate Origin headers with exact matching, avoid reflecting Origin header without validation.': 'فقط originهای مورد اعتماد را دقیق allowlist کنید، هرگز wildcard را همراه credentials به کار نبرید، هدر Origin را با تطبیق دقیق اعتبارسنجی کنید و از بازتاب Origin بدون بررسی خودداری کنید.',
  'Remote code execution, file system access, internal service access, sensitive data exfiltration, complete server compromise.': 'اجرای کد از راه دور، دسترسی به فایل سیستم، دسترسی به سرویس‌های داخلی، خروج داده‌های حساس و تسخیر کامل سرور.',
  'Never allow users to control template content, use sandboxed template engines, sanitize and escape all user input before template rendering, use logic-less templates where possible.': 'هرگز اجازه ندهید کاربر محتوای template را کنترل کند، از template engineهای sandboxed استفاده کنید و پیش از render همه ورودی‌ها را پاک‌سازی و escape کنید.',
  'Unauthorized actions performed by user, social media manipulation, account settings changes, unauthorized purchases, Like/Share hijacking.': 'انجام اقدام‌های غیرمجاز به نام کاربر، دستکاری شبکه‌های اجتماعی، تغییر تنظیمات حساب، خریدهای غیرمجاز و ربودن Like/Share.',
  'Implement X-Frame-Options header (DENY/SAMEORIGIN), use Content Security Policy frame-ancestors directive, implement framebusting JavaScript (defense in depth).': 'هدر X-Frame-Options را با DENY یا SAMEORIGIN اعمال کنید، از دستور frame-ancestors در CSP استفاده کنید و به‌عنوان دفاع چندلایه framebusting JavaScript داشته باشید.',
  'Authentication bypass, data exfiltration, data manipulation, denial of service, in some cases code execution.': 'دور زدن احراز هویت، خروج داده، دستکاری داده، ایجاد اختلال در سرویس و در برخی موارد اجرای کد.',
  'Use query builder libraries, validate and sanitize input types, use schema validation, avoid passing user input directly to query operators, disable JavaScript execution in MongoDB.': 'از کتابخانه‌های query builder استفاده کنید، نوع ورودی‌ها را اعتبارسنجی و پاک‌سازی کنید، از schema validation بهره ببرید، ورودی کاربر را مستقیم به operatorهای query ندهید و اجرای JavaScript را در MongoDB غیرفعال کنید.',
  'Bypass security controls, gain unauthorized access to sensitive data, hijack other users\' requests, XSS, cache poisoning, credential capture.': 'دور زدن کنترل‌های امنیتی، دسترسی غیرمجاز به داده‌های حساس، ربودن درخواست‌های کاربران دیگر، XSS، cache poisoning و جمع‌آوری اعتبارنامه.',
  'Use HTTP/2 end-to-end, disable reuse of back-end connections, use consistent parsing between front-end and back-end, disable ambiguous request support.': 'از HTTP/2 به‌صورت end-to-end استفاده کنید، بازاستفاده از اتصال‌های back-end را غیرفعال کنید، parsing یکسان بین front-end و back-end داشته باشید و پشتیبانی از درخواست‌های مبهم را غیرفعال کنید.',
  'Remote code execution, XSS via malicious SVG/HTML, DoS via zip bombs, phishing via malicious documents, server compromise.': 'اجرای کد از راه دور، XSS از طریق SVG/HTML مخرب، DoS با zip bomb، فیشینگ با اسناد مخرب و تسخیر سرور.',
  'Validate file type by content (magic bytes), use allowlist for permitted types, rename uploaded files, store outside web root, scan with antivirus, use separate domain for user content.': 'نوع فایل را با بررسی محتوا و magic bytes اعتبارسنجی کنید، برای نوع‌های مجاز از allowlist استفاده کنید، فایل‌های بارگذاری‌شده را تغییر نام دهید، بیرون از web root نگه دارید، با آنتی‌ویروس اسکن کنید و برای محتوای کاربر دامنه جدا داشته باشید.',
  'Avoid deserializing data from untrusted sources, use integrity checks (HMAC) on serialized data, use safe serialization formats (JSON), implement deserialization firewalls.': 'از deserialize کردن داده منابع غیرقابل اعتماد خودداری کنید، روی داده serialized بررسی یکپارچگی مثل HMAC اجرا کنید، از قالب‌های امن‌تر مثل JSON استفاده کنید و دیوار دفاعی deserialization داشته باشید.',
  'Schema disclosure, authentication bypass, DoS via complex queries, authorization bypass, injection attacks, mass data exfiltration.': 'افشای schema، دور زدن احراز هویت، DoS با queryهای پیچیده، دور زدن مجوزدهی، حمله‌های تزریق و خروج انبوه داده.',
  'Disable introspection in production, implement query depth limiting, use query cost analysis, apply field-level authorization in resolvers, rate limit queries, validate all inputs.': 'introspection را در محیط production غیرفعال کنید، محدودیت عمق query اجرا کنید، از تحلیل هزینه query استفاده کنید، در resolverها مجوزدهی در سطح field اجرا کنید، queryها را rate limit کنید و همه ورودی‌ها را اعتبارسنجی کنید.',
  'Account takeover, unauthorized data access to third-party resources, privilege escalation, cross-site request forgery on authorization.': 'تصاحب حساب، دسترسی غیرمجاز به منابع طرف سوم، ارتقای سطح دسترسی و جعل درخواست در فرایند authorization.',
  'Always use and validate state parameter, use PKCE for public clients, validate redirect URIs strictly, use short-lived authorization codes, implement proper token storage.': 'همیشه از state استفاده کنید و آن را اعتبارسنجی کنید، برای clientهای عمومی PKCE را به کار ببرید، redirect URIها را دقیق بررسی کنید، authorization codeهای کوتاه‌عمر داشته باشید و توکن‌ها را امن نگه‌داری کنید.',
  'Double-spending, inventory manipulation, duplicate coupon use, bypassing single-use limits, account balance manipulation.': 'دوباره‌خرج کردن، دستکاری موجودی، استفاده تکراری از کوپن، دور زدن محدودیت‌های یک‌بارمصرف و دستکاری موجودی حساب.',
  'Use database transactions with proper isolation levels, implement locking mechanisms, use atomic operations, validate state changes atomically, use idempotency keys.': 'از transactionهای پایگاه داده با isolation level مناسب استفاده کنید، locking را اجرا کنید، عملیات atomic به کار ببرید، تغییرات وضعیت را به شکل atomic بررسی کنید و از idempotency key استفاده کنید.',
  'Financial loss, data integrity issues, unauthorized access, bypassing security controls, abusing application features for unintended purposes.': 'زیان مالی، مشکل یکپارچگی داده، دسترسی غیرمجاز، دور زدن کنترل‌های امنیتی و سوءاستفاده از قابلیت‌های برنامه برای هدف‌های ناخواسته.',
  'Threat model all business processes, implement server-side validation for all business rules, test edge cases and boundary conditions, implement proper state machine validation.': 'برای همه فرایندهای کسب‌وکار threat model انجام دهید، همه قوانین را سمت سرور اعتبارسنجی کنید، edge caseها و boundary conditionها را آزمایش کنید و state machine درست اجرا کنید.',
  'Stored XSS affecting all users who receive poisoned cache, denial of service, JavaScript injection, cookie theft.': 'Stored XSS برای همه کاربرانی که پاسخ cache‌شده مسموم را دریافت می‌کنند، اختلال در سرویس، تزریق JavaScript و سرقت کوکی.',
  'Avoid using unkeyed inputs in responses, configure cache to include all relevant headers in cache keys, use Cache-Control: no-store for sensitive responses, implement cache key normalization.': 'از ورودی‌هایی که در cache key نیستند در پاسخ استفاده نکنید، cache را طوری پیکربندی کنید که هدرهای مهم در cache key لحاظ شوند، برای پاسخ‌های حساس از Cache-Control: no-store استفاده کنید و cache key normalization اجرا کنید.',
  Live: 'زنده',
  'min short': 'دقیقه',
  Authentication: 'احراز هویت',
  'Access Control': 'کنترل دسترسی',
  'NoSQL Injection': 'تزریق NoSQL',
  'Business Logic': 'منطق کسب‌وکار',
  Deserialization: 'Deserialization',
  'SQL injection in WHERE clause – retrieve hidden data': 'تزریق SQL در شرط WHERE — بازیابی داده‌های پنهان',
  'The product category filter uses an SQL query to return products. The results are displayed in a vulnerable way. To solve this lab, perform an SQL injection attack that causes the application to display all products, including unreleased items.': 'فیلتر دسته‌بندی محصول برای نمایش محصولات از یک query SQL استفاده می‌کند. نتایج به شکلی آسیب‌پذیر نمایش داده می‌شوند. برای حل این آزمایشگاه، حمله تزریق SQL انجام دهید تا برنامه همه محصولات، حتی موارد منتشرنشده را نمایش دهد.',
  'SQL injection – login bypass': 'تزریق SQL — دور زدن ورود',
  "The login page uses SQL to authenticate users. The application constructs the SQL query using string concatenation with user-supplied input. To solve the lab, log in as the administrator user without knowing the password.": 'صفحه ورود برای احراز هویت کاربران از SQL استفاده می‌کند. برنامه query را با چسباندن رشته‌ها و ورودی کاربر می‌سازد. برای حل آزمایشگاه، بدون دانستن رمز عبور به‌عنوان administrator وارد شوید.',
  'SQL injection UNION attack – determining columns': 'حمله UNION در SQL injection — تعیین تعداد ستون‌ها',
  'The application is vulnerable to SQL injection via the category parameter. Determine the number of columns returned by the query using a UNION-based attack technique.': 'برنامه از طریق پارامتر category در برابر SQL injection آسیب‌پذیر است. با تکنیک حمله مبتنی بر UNION تعداد ستون‌های برگشتی query را مشخص کنید.',
  'SQL injection UNION attack – extract data from other tables': 'حمله UNION در SQL injection — استخراج داده از جدول‌های دیگر',
  'The database contains a table called users with columns username and password. Use a UNION-based SQL injection to retrieve all usernames and passwords.': 'پایگاه داده جدولی به نام users با ستون‌های username و password دارد. با SQL injection مبتنی بر UNION همه نام‌های کاربری و رمزها را بازیابی کنید.',
  'Blind SQL injection with boolean-based detection': 'SQL injection کور با تشخیص مبتنی بر boolean',
  "The application uses a tracking cookie for analytics. The SQL query is evaluated but results are not returned. The application's behavior differs based on whether the query returns results. Use boolean-based blind SQL injection to determine the admin password length.": 'برنامه برای تحلیل از cookie رهگیری استفاده می‌کند. query اجرا می‌شود اما نتیجه برگردانده نمی‌شود. رفتار برنامه بسته به نتیجه query تغییر می‌کند. با SQL injection کور مبتنی بر boolean طول رمز مدیر را پیدا کنید.',
  'Reflected XSS into HTML context with no encoding': 'XSS بازتابی در زمینه HTML بدون encoding',
  "The search blog functionality reflects the search term in the response without any encoding. Inject a script that calls alert(document.domain) to demonstrate the XSS vulnerability.": 'قابلیت جستجوی وبلاگ عبارت جستجو را بدون هیچ encoding در پاسخ بازتاب می‌دهد. برای نمایش آسیب‌پذیری XSS اسکریپتی تزریق کنید که alert(document.domain) را اجرا کند.',
  'Stored XSS into HTML context': 'XSS ذخیره‌شده در زمینه HTML',
  "The blog comment functionality stores user input and displays it to other users without proper encoding. Inject a stored XSS payload that will execute for every user who views the comment.": 'قابلیت نظرهای وبلاگ ورودی کاربر را ذخیره کرده و بدون encoding درست به کاربران دیگر نمایش می‌دهد. یک payload ذخیره‌شده XSS تزریق کنید که برای هر کاربر مشاهده‌کننده نظر اجرا شود.',
  'DOM XSS using document.write with location.search': 'DOM XSS با document.write و location.search',
  "The search functionality uses document.write() with data from location.search. Exploit this DOM-based XSS to execute JavaScript. The script writes: `document.write('<img src=\"/resources/images/tracker.gif?searchTerms='+query+'\">')`": 'قابلیت جستجو از document.write() با داده location.search استفاده می‌کند. از این DOM XSS برای اجرای JavaScript سوءاستفاده کنید. اسکریپت این مقدار را می‌نویسد: `document.write(...)`',
  'Stored XSS into onClick event with HTML encoding': 'XSS ذخیره‌شده در رویداد onClick با HTML encoding',
  "The website links to user-supplied website URLs in the href attribute of anchor tags, and also in onclick event handlers. Bypass the HTML encoding to achieve XSS.": 'سایت URLهای واردشده توسط کاربر را هم در ویژگی href لینک‌ها و هم در handlerهای onclick قرار می‌دهد. با دور زدن HTML encoding به XSS برسید.',
  'CSRF vulnerability with no defenses': 'آسیب‌پذیری CSRF بدون دفاع',
  "The email change functionality has no CSRF defenses. Craft a cross-site request forgery attack that changes the victim's email address to one you control.": 'قابلیت تغییر ایمیل هیچ دفاعی در برابر CSRF ندارد. حمله CSRF بسازید که ایمیل قربانی را به ایمیلی تحت کنترل شما تغییر دهد.',
  'CSRF where token is not tied to user session': 'CSRF با توکنی که به نشست کاربر متصل نیست',
  'The CSRF token is validated but not tied to the user session. Obtain a valid CSRF token from your own account and use it in a CSRF attack against another user.': 'توکن CSRF اعتبارسنجی می‌شود اما به نشست کاربر متصل نیست. از حساب خودتان یک توکن معتبر بگیرید و در حمله CSRF علیه کاربر دیگر استفاده کنید.',
  'Basic SSRF against the local server': 'SSRF ساده علیه سرور محلی',
  'The stock check feature fetches data from an internal URL. The URL is taken from the request body and no validation is performed. Access the admin panel at http://localhost/admin.': 'قابلیت بررسی موجودی از یک URL داخلی داده می‌گیرد. URL از بدنه درخواست خوانده می‌شود و اعتبارسنجی ندارد. به پنل مدیر در http://localhost/admin دسترسی بگیرید.',
  'SSRF to access AWS EC2 metadata': 'SSRF برای دسترسی به metadata در AWS EC2',
  'This application runs on AWS EC2. Use SSRF to access the instance metadata service and retrieve sensitive information including IAM credentials.': 'این برنامه روی AWS EC2 اجرا می‌شود. با SSRF به سرویس metadata نمونه دسترسی بگیرید و اطلاعات حساس از جمله IAM credentials را بازیابی کنید.',
  'File path traversal – simple case': 'پیمایش مسیر فایل — حالت ساده',
  'The application serves images via a filename parameter. Attempt to traverse outside the intended directory to read the /safe/training/file.txt file.': 'برنامه تصاویر را از طریق پارامتر filename ارائه می‌کند. تلاش کنید از پوشه مجاز خارج شوید و فایل /safe/training/file.txt را بخوانید.',
  'Path traversal with validation bypass': 'پیمایش مسیر با دور زدن اعتبارسنجی',
  'The application attempts to strip ../ sequences from the filename input but the sanitization can be bypassed. Retrieve the /safe/training/file.txt file despite the filtering.': 'برنامه تلاش می‌کند دنباله‌های ../ را از نام فایل حذف کند اما پاک‌سازی قابل دور زدن است. با وجود فیلتر، فایل /safe/training/file.txt را بازیابی کنید.',
  "IDOR – access another user's profile": 'IDOR — دسترسی به پروفایل کاربر دیگر',
  "The user profile endpoint uses a numeric user ID in the URL. Test whether you can access other users' profiles by changing the ID parameter.": 'endpoint پروفایل کاربر از یک شناسه عددی در URL استفاده می‌کند. بررسی کنید آیا با تغییر پارامتر ID می‌توانید به پروفایل کاربران دیگر دسترسی بگیرید.',
  'IDOR – access order history': 'IDOR — دسترسی به تاریخچه سفارش',
  "The order history endpoint exposes order details based on an order ID in the URL. Find and access another customer's order records.": 'endpoint تاریخچه سفارش بر اساس order ID در URL جزئیات سفارش را نمایش می‌دهد. رکوردهای سفارش مشتری دیگر را پیدا کرده و به آن‌ها دسترسی بگیرید.',
  'JWT authentication bypass via unverified signature': 'دور زدن احراز هویت JWT با امضای بررسی‌نشده',
  "The application uses JWT authentication but doesn't properly validate the signature. Modify your JWT to change the algorithm to 'none' and access the admin panel.": 'برنامه از احراز هویت JWT استفاده می‌کند اما امضا را درست اعتبارسنجی نمی‌کند. JWT خود را تغییر دهید، الگوریتم را به none ببرید و به پنل مدیر دسترسی بگیرید.',
  'JWT authentication bypass via weak secret': 'دور زدن احراز هویت JWT با secret ضعیف',
  'The application uses HS256 JWT with a weak secret key. Brute-force the secret and forge a valid admin token.': 'برنامه از JWT با HS256 و secret ضعیف استفاده می‌کند. secret را brute-force کنید و یک توکن معتبر مدیر بسازید.',
  'JWT authentication bypass via algorithm confusion': 'دور زدن احراز هویت JWT با سردرگمی الگوریتم',
  "The application allows both RS256 and HS256 algorithms. Exploit algorithm confusion by using the server's public key as the HMAC secret for HS256.": 'برنامه هر دو الگوریتم RS256 و HS256 را می‌پذیرد. با استفاده از public key سرور به‌عنوان HMAC secret برای HS256 از سردرگمی الگوریتم سوءاستفاده کنید.',
  'OS command injection – simple case': 'تزریق فرمان سیستم‌عامل — حالت ساده',
  'The application provides a ping functionality for network diagnostics. The IP address is passed directly to a system command. Inject OS commands to execute arbitrary system commands.': 'برنامه برای عیب‌یابی شبکه قابلیت ping دارد. آدرس IP مستقیم به فرمان سیستم داده می‌شود. فرمان‌های سیستم‌عامل تزریق کنید تا دستور دلخواه اجرا شود.',
  'Blind OS command injection with out-of-band detection': 'تزریق فرمان کور با تشخیص out-of-band',
  "The feedback submission form is vulnerable to blind OS command injection. There's no visible output, but you can use time delays and out-of-band techniques to confirm and exploit the vulnerability.": 'فرم ارسال بازخورد در برابر تزریق فرمان کور آسیب‌پذیر است. خروجی قابل مشاهده‌ای وجود ندارد، اما می‌توانید با تأخیر زمانی و تکنیک‌های out-of-band آسیب‌پذیری را تأیید و بهره‌برداری کنید.',
  'Exploiting XXE to retrieve files': 'بهره‌برداری از XXE برای بازیابی فایل‌ها',
  'The application uses an XML-based stock check API. Inject an external entity to retrieve the contents of /safe/training/file.txt from the server.': 'برنامه از API بررسی موجودی مبتنی بر XML استفاده می‌کند. یک external entity تزریق کنید تا محتوای /safe/training/file.txt از سرور بازیابی شود.',
  'Exploiting XXE to perform SSRF': 'بهره‌برداری از XXE برای انجام SSRF',
  'The application is vulnerable to XXE. Use XXE to perform SSRF and access the AWS metadata endpoint at http://metadata.training.local.': 'برنامه در برابر XXE آسیب‌پذیر است. از XXE برای انجام SSRF و دسترسی به endpoint metadata در http://metadata.training.local استفاده کنید.',
  'Server-Side Template Injection – basic detection': 'تزریق Template سمت سرور — تشخیص ساده',
  'The application renders user input in a template. Detect SSTI and identify the template engine by injecting mathematical expressions.': 'برنامه ورودی کاربر را داخل template رندر می‌کند. با تزریق عبارت‌های ریاضی SSTI را تشخیص دهید و template engine را شناسایی کنید.',
  'SSTI – Jinja2 Remote Code Execution': 'SSTI — اجرای کد از راه دور در Jinja2',
  'The application uses Jinja2 and is vulnerable to SSTI. Escalate from basic SSTI to remote code execution by accessing Python built-in functions.': 'برنامه از Jinja2 استفاده می‌کند و در برابر SSTI آسیب‌پذیر است. با دسترسی به توابع داخلی Python از SSTI ساده به اجرای کد از راه دور برسید.',
  'CORS vulnerability with basic origin reflection': 'آسیب‌پذیری CORS با بازتاب ساده Origin',
  "The application reflects the Origin header in the Access-Control-Allow-Origin response header with credentials allowed. Exploit this to steal the victim's API key.": 'برنامه هدر Origin را در پاسخ Access-Control-Allow-Origin بازتاب می‌دهد و credentials هم مجاز است. از این مشکل برای سرقت API key قربانی سوءاستفاده کنید.',
  'Basic clickjacking attack': 'حمله ساده Clickjacking',
  "The target website doesn't use X-Frame-Options or CSP frame-ancestors, making it vulnerable to clickjacking. Construct a clickjacking attack that causes the victim to delete their account.": 'سایت هدف از X-Frame-Options یا CSP frame-ancestors استفاده نمی‌کند و در برابر clickjacking آسیب‌پذیر است. حمله‌ای بسازید که قربانی را وادار به حذف حساب کند.',
  'NoSQL injection – login bypass': 'تزریق NoSQL — دور زدن ورود',
  'The application uses MongoDB to authenticate users. The login form sends JSON data directly to the MongoDB query. Bypass authentication using NoSQL operators.': 'برنامه برای احراز هویت کاربران از MongoDB استفاده می‌کند. فرم ورود داده JSON را مستقیم به query MongoDB می‌فرستد. با operatorهای NoSQL احراز هویت را دور بزنید.',
  'Business logic – negative quantity purchase': 'منطق کسب‌وکار — خرید با تعداد منفی',
  'The shopping cart allows quantity to be set to any integer value. Use negative quantities to manipulate the total price and potentially get items for free or get a refund.': 'سبد خرید اجازه می‌دهد تعداد هر مقدار صحیحی باشد. با تعداد منفی قیمت کل را دستکاری کنید و شاید کالا را رایگان بگیرید یا refund ایجاد کنید.',
  'Business logic – 2FA bypass': 'منطق کسب‌وکار — دور زدن 2FA',
  'After completing the first authentication factor (password), the application redirects to the 2FA page. Test if you can bypass the 2FA step by directly navigating to authenticated pages.': 'پس از تکمیل عامل اول احراز هویت یعنی password، برنامه به صفحه 2FA هدایت می‌کند. بررسی کنید آیا با رفتن مستقیم به صفحه‌های احراز هویت‌شده می‌توانید مرحله 2FA را دور بزنید.',
  'HTTP request smuggling – basic CL.TE vulnerability': 'HTTP request smuggling — آسیب‌پذیری ساده CL.TE',
  "The front-end server uses Content-Length and the back-end uses Transfer-Encoding. Exploit this discrepancy to smuggle a request. To solve the lab, smuggle a request so that the next user's request is captured.": 'سرور front-end از Content-Length و سرور back-end از Transfer-Encoding استفاده می‌کند. از این اختلاف برای smuggle کردن درخواست سوءاستفاده کنید. برای حل آزمایشگاه، درخواستی را smuggle کنید تا درخواست کاربر بعدی گرفته شود.',
  'Race condition – coupon code reuse': 'Race condition — استفاده دوباره از کد تخفیف',
  'The coupon redemption system has a race condition. The check and update are not atomic. Send concurrent requests to use the same coupon code multiple times.': 'سیستم استفاده از کوپن race condition دارد. بررسی و به‌روزرسانی atomic نیستند. درخواست‌های همزمان بفرستید تا از یک کد کوپن چند بار استفاده شود.',
  'File upload – bypass content type validation': 'File Upload — دور زدن اعتبارسنجی Content-Type',
  'The file upload functionality validates the Content-Type header but not the actual file content. Upload a PHP webshell by manipulating the Content-Type header.': 'قابلیت بارگذاری فایل هدر Content-Type را بررسی می‌کند اما محتوای واقعی فایل را نه. با دستکاری Content-Type یک PHP webshell بارگذاری کنید.',
  'File upload – Zip Slip path traversal': 'File Upload — پیمایش مسیر با Zip Slip',
  'The application extracts uploaded ZIP files. Craft a malicious ZIP file where entries have path traversal sequences in their filenames to write files outside the extraction directory.': 'برنامه فایل‌های ZIP بارگذاری‌شده را استخراج می‌کند. یک ZIP مخرب بسازید که entryهای آن در نام فایل دنباله‌های پیمایش مسیر داشته باشند تا فایل‌ها بیرون از پوشه استخراج نوشته شوند.',
  'GraphQL – information disclosure via introspection': 'GraphQL — افشای اطلاعات از طریق introspection',
  'The GraphQL API has introspection enabled in production. Use introspection to discover all types, fields, and queries, including hidden administrative functionality.': 'API GraphQL در production قابلیت introspection را فعال دارد. از introspection برای کشف همه typeها، fieldها و queryها، از جمله قابلیت‌های مدیریتی پنهان، استفاده کنید.',
  'GraphQL – batching attack to bypass rate limiting': 'GraphQL — حمله batching برای دور زدن rate limit',
  'The OTP verification uses GraphQL mutations. Rate limiting is applied per request but not per operation. Use GraphQL batching to send hundreds of OTP guesses in a single request.': 'تأیید OTP از mutationهای GraphQL استفاده می‌کند. rate limit برای هر درخواست اعمال می‌شود، نه هر operation. با GraphQL batching صدها حدس OTP را در یک درخواست بفرستید.',
  'PHP deserialization – cookie manipulation': 'PHP deserialization — دستکاری cookie',
  'The application stores session data in a PHP-serialized cookie. Modify the serialized object to grant yourself admin privileges.': 'برنامه داده نشست را در cookie سریال‌شده PHP نگه می‌دارد. شیء serialized را تغییر دهید تا به خودتان دسترسی مدیر بدهید.',
  'Web cache poisoning to deliver stored XSS': 'Web Cache Poisoning برای رساندن XSS ذخیره‌شده',
  'The application reflects the X-Forwarded-Host header in the response, which gets cached. Poison the cache with a malicious X-Forwarded-Host to deliver XSS to all visitors.': 'برنامه هدر X-Forwarded-Host را در پاسخ بازتاب می‌دهد و پاسخ cache می‌شود. با X-Forwarded-Host مخرب cache را مسموم کنید تا XSS به همه بازدیدکنندگان برسد.',
  'OAuth – CSRF via missing state parameter': 'OAuth — CSRF به‌دلیل نبود پارامتر state',
  "The OAuth flow doesn't implement the state parameter, making it vulnerable to CSRF. Forge a link that connects an attacker's OAuth account to a victim's application account.": 'جریان OAuth پارامتر state را پیاده‌سازی نکرده و در برابر CSRF آسیب‌پذیر است. لینکی جعل کنید که حساب OAuth مهاجم را به حساب برنامه قربانی وصل کند.',
  'Blind SQL injection with time delays': 'SQL injection کور با تأخیر زمانی',
  "The application doesn't show any output from SQL queries but is vulnerable to blind SQL injection. Use time delays to confirm and enumerate the database.": 'برنامه خروجی queryهای SQL را نشان نمی‌دهد اما در برابر SQL injection کور آسیب‌پذیر است. با تأخیر زمانی آسیب‌پذیری را تأیید کرده و پایگاه داده را enumerate کنید.',
  'Reflected XSS with CSP bypass': 'XSS بازتابی با دور زدن CSP',
  'The application uses Content Security Policy to prevent XSS but the policy is misconfigured. Find a CSP bypass to execute arbitrary JavaScript.': 'برنامه برای جلوگیری از XSS از Content Security Policy استفاده می‌کند اما سیاست بد پیکربندی شده است. راهی برای دور زدن CSP پیدا کنید تا JavaScript دلخواه اجرا شود.',
  'Username enumeration via different responses': 'شمارش نام کاربری با پاسخ‌های متفاوت',
  'The login form behaves differently when an incorrect username vs an incorrect password is provided. Use this difference to enumerate valid usernames.': 'فرم ورود وقتی نام کاربری اشتباه است با وقتی رمز اشتباه است رفتار متفاوتی دارد. از این تفاوت برای enumerate کردن نام‌های کاربری معتبر استفاده کنید.',
  'Brute-force attack on login': 'حمله brute-force روی ورود',
  'The login page has no effective brute-force protection. Perform a credential stuffing attack using a list of common passwords to gain access.': 'صفحه ورود محافظت مؤثری در برابر brute-force ندارد. با فهرستی از رمزهای رایج حمله credential stuffing انجام دهید تا دسترسی بگیرید.',
  'Unprotected admin functionality': 'قابلیت مدیریتی محافظت‌نشده',
  'The admin panel is not properly protected. It relies on security through obscurity - the URL is not linked but accessible. Find and access the admin panel.': 'پنل مدیر درست محافظت نشده است. به امنیت از طریق پنهان‌کاری تکیه دارد؛ URL لینک نشده اما قابل دسترسی است. پنل مدیر را پیدا کرده و وارد شوید.',
  'User-controlled key for horizontal privilege escalation': 'کلید قابل کنترل کاربر برای ارتقای افقی دسترسی',
  "The application uses a GUID to identify user accounts in the URL. Test if you can access other users' accounts by finding their GUIDs.": 'برنامه برای شناسایی حساب‌های کاربری در URL از GUID استفاده می‌کند. بررسی کنید آیا با پیدا کردن GUID کاربران دیگر می‌توانید به حساب‌هایشان دسترسی بگیرید.',
});

export function faLabel(value: string, replacements: Record<string, string | number> = {}): string {
  let translated = faOverrides[value] ?? faLabels[value] ?? faContent[value] ?? value;

  for (const [key, replacement] of Object.entries(replacements)) {
    translated = translated.replaceAll(`{{${key}}}`, String(replacement));
  }

  return translated;
}

