import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { adminWriteups, deleteWriteup, transitionWriteup, type Writeup } from '../../lib/writeupApi';
import { useLanguage } from '../../i18n/LanguageContext';

export function AdminWriteups() {
  const { locale } = useLanguage();
  const [rows, setRows] = useState<Writeup[]>([]);
  const [error, setError] = useState('');
  const reload = async () => { try { const response = await adminWriteups(); setRows(response.data ?? []); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Request failed.'); } };
  useEffect(() => { void reload(); }, []);
  const act = async (row: Writeup, operation: string) => { if (['archive', 'delete', 'publish'].includes(operation) && !window.confirm(`${operation}?`)) return; try { operation === 'delete' ? await deleteWriteup(row.id) : await transitionWriteup(row.id, operation); await reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Request failed.'); } };
  return <main className="mx-auto min-h-screen max-w-7xl px-4 py-8"><div className="mb-6 flex items-center justify-between"><h1 className="text-3xl font-black">{locale === 'fa' ? 'رایت‌آپ‌ها' : 'Write-ups'}</h1><Link to="/admin/writeups/create" className="rounded-xl bg-emerald-400 px-4 py-2 font-bold text-slate-950">Create write-up</Link></div>{error && <p role="alert" className="mb-4 rounded-xl bg-red-500/15 p-3 text-red-200">{error}</p>}<div className="overflow-x-auto rounded-2xl border border-slate-800"><table className="min-w-full text-start text-sm"><thead className="bg-slate-900"><tr><th className="px-4 py-3">Title</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{rows.map((row) => { const translation = row.translations.find((item) => item.locale === locale) ?? row.translations[0]; return <tr key={row.id} className="border-t border-slate-800"><td className="px-4 py-3"><Link to={`/admin/writeups/${row.id}`} className="font-bold text-emerald-300">{translation?.title ?? row.original_title}</Link></td><td className="px-4 py-3">{row.status}</td><td className="px-4 py-3"><div className="flex flex-wrap gap-2"><Link to={`/admin/writeups/${row.id}`} className="text-emerald-300">View</Link>{row.status === 'archived' ? <button onClick={() => void act(row, 'restore')} className="text-cyan-300">Restore draft</button> : <button onClick={() => void act(row, 'archive')} className="text-amber-300">Archive</button>}{row.status === 'draft' && <button onClick={() => void act(row, 'submit')} className="text-cyan-300">Submit</button>}{row.status === 'pending_review' && <button onClick={() => void act(row, 'approve')} className="text-emerald-300">Approve</button>}{row.status === 'approved' && <><button onClick={() => void act(row, 'review-translations')} className="text-cyan-300">Review translations</button><button onClick={() => void act(row, 'publish')} className="text-emerald-300">Publish</button></>}<button onClick={() => void act(row, 'delete')} className="text-red-300">Delete</button></div></td></tr>; })}</tbody></table></div></main>;
}
